### ISSUE TITLE
Folly failing to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by vj-rajesh-kumar** [facebook/folly#104]
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -I/home/cassandra/Downloads/double-conversion/ -std=gnu++0x -g -O2 -MT experimental/wangle/ssl/SSLSessionCacheManager.lo -MD -MP -MF experimental/wangle/ssl/.deps/SSLSessionCacheManager.Tpo -c experimental/wangle/ssl/SSLSessionCacheManager.cpp  -fPIC -DPIC -o experimental/wangle/ssl/.libs/SSLSessionCacheManager.o
experimental/wangle/ssl/SSLSessionCacheManager.cpp:32:12: error: expected constructor, destructor, or type conversion before '(' token
 DEFINE_bool(dcache_unit_test, false, "All VIPs share one session cache");
            ^
experimental/wangle/ssl/SSLSessionCacheManager.cpp: In constructor 'folly::SSLSessionCacheManager::SSLSessionCacheManager(uint32_t, uint32_t, folly::SSLContext_, const folly::SocketAddress&, const string&, folly::EventBase_, folly::SSLStats_, const std::shared_ptrfolly::SSLCacheProvider&)':
experimental/wangle/ssl/SSLSessionCacheManager.cpp:86:8: error: 'FLAGS_dcache_unit_test' was not declared in this scope
   if (!FLAGS_dcache_unit_test && !context.empty()) {
        ^
make[2]: *_\* [experimental/wangle/ssl/SSLSessionCacheManager.lo] Error 1
make[2]: Leaving directory `/home/cassandra/Downloads/folly/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/cassandra/Downloads/folly/folly/folly'
make: **\* [all] Error 2

Facing the following error while attempting to make.

**Comment by daniel-lucio** [comment]
For CentOS, check #929
