### PR TITLE
fix: compatible with lower clang version

### PR DESCRIPTION
**Pull request by YouSenRong**
* At least the Clang 11.0.0 can support "asm volatile inline", the lower version (e.g. 9.0.1) can only support "asm volatile".

### CODE REVIEW

**Comment by YouSenRong** [comment]
When I compile the compile the master of folly with Clang compiler (9.0.1), I met a problem as bellow. 
```
"/folly/folly/chrono/Hardware.h:94:16: error: expected '(' after 'asm'
  asm volatile inline("
```

And the problem can be reproduce on Compiler Explorer.
When compile with Clang 9.0.1, the problem can be reproduced.
image
After I removed the "inline" keyword, the problem was solved.
image

Besides, I found that, the problem can also be solved when compile with at least Clang 11.0.0, 
image

And I added the condition of __clang__major__ to make the code work.
```
  #if __clang_major__ >= 11
    asm volatile inline(
  #else 
    asm volatile(
  #endif
```

**Comment by YouSenRong** [comment]
Hi, will this pr be merged, or is there any thing else should be done before being merged?

**Comment by Orvid** [comment]
I think this will probably be able to be merged, though I've had to make some minor changes internally to make sure that GCC still has the right behavior. The tests are running on the new version now.

**Comment by YouSenRong** [comment]
Ok, Thanks! @Orvid
