### ISSUE TITLE
Unable to compile on CentOS release 6.2 (Final)

### ISSUE THREAD

**Issue by preillyme** [facebook/folly#31]
g++ -DHAVE_CONFIG_H -I.  -I../. -I./io -I./test -lstdc++ -std=gnu++0x -pthread -I/usr/include -I/home/preilly/double-conversion/src/ -lboost_thread-mt -lboost_system -g -O2 -MT GenerateFingerprintTables.o -MD -MP -MF .deps/GenerateFingerprintTables.Tpo -c -o GenerateFingerprintTables.o `test -f 'build/GenerateFingerprintTables.cpp' || echo './'`build/GenerateFingerprintTables.cpp
mv -f .deps/GenerateFingerprintTables.Tpo .deps/GenerateFingerprintTables.Po
/bin/sh ./libtool --tag=CXX   --mode=link g++ -lboost_thread-mt -lboost_system -g -O2  -L/home/preilly/double-conversion/ -o generate_fingerprint_tables GenerateFingerprintTables.o libfolly.la -ldouble_conversion_pic -lgflags -lglog
libtool: link: g++ -g -O2 -o .libs/generate_fingerprint_tables GenerateFingerprintTables.o  -L/home/preilly/double-conversion/ ./.libs/libfolly.so -lboost_system -lboost_thread-mt -lpthread -ldouble_conversion_pic /usr/lib64/libgflags.so -lglog -pthread -Wl,-rpath -Wl,/usr/local/lib
./.libs/libfolly.so: undefined reference to `boost::system::system_category()'
./.libs/libfolly.so: undefined reference to `boost::system::generic_category()'
collect2: error: ld returned 1 exit status
make[2]: *** [generate_fingerprint_tables] Error 1
make[2]: Leaving directory `/home/preilly/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/preilly/folly/folly'
make: *** [all] Error 2

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-2** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by daniel-lucio** [comment]
For CentOS, check #929
