### ISSUE TITLE
Fail to build on centos6.6

### ISSUE THREAD

**Issue by yjr930** [facebook/folly#908]
I build folly and it says:

folly/folly/portability/Time.cpp:276:2: error: #error No clock_gettime(3) compatibility wrapper available for this platform.

environment:
g++ (GCC) 8.2.0
cmake 3.12.0
CentOS release 6.6 (Final)

**Comment by daniel-lucio** [comment]
Check #929

**Comment by agah-pt** [comment]
Hi, 

I just faced the same problem and got it fixed by adding -Wl,-lrt to my CFLAGS
Do more modern compilers not need such flag?

**Comment by yanke1311** [comment]
I faced the same problem, and the solution above was not worked for me

**Comment by yanke1311** [comment]
Hgg

> Hi,
> 
> I just faced the same problem and got it fixed by adding -Wl,-lrt to my CFLAGS
> 
> My version:
> 
> ```
>  gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
>  Copyright (C) 2016 Free Software Foundation, Inc.
>  This is free software; see the source for copying conditions.  There is NO
>  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

hi, can you tell me where to append CFLAGS? thanks!

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because folly no longer targets CentOS 6.
