### ISSUE TITLE
Doesn't build with recent glog 0.6.0

### ISSUE THREAD

**Issue by yurikoles** [facebook/folly#1759]
```
/tmp/folly-20220411-15487-161673u/folly-2022.03.21.00/folly/init/Init.cpp: In function 'void folly::init(int*, char***, folly::InitOptions)':
  /tmp/folly-20220411-15487-161673u/folly-2022.03.21.00/folly/init/Init.cpp:79:34: error: invalid conversion from 'void (*)() noexcept' to 'google::logging_fail_func_t' {aka 'void (*)() __attribute__((noreturn))'} [-fpermissive]
     79 |   google::InstallFailureFunction(abort);
        |                                  ^~~~~
        |                                  |
        |                                  void (*)() noexcept
  In file included from /tmp/folly-20220411-15487-161673u/folly-2022.03.21.00/folly/init/Init.cpp:19:
  /home/linuxbrew/.linuxbrew/include/glog/logging.h:642:61: note:   initializing argument 1 of 'void google::InstallFailureFunction(google::logging_fail_func_t)'
    642 | GLOG_EXPORT void InstallFailureFunction(logging_fail_func_t fail_func);
        |                                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
  At global scope:
```

**Comment by yurikoles** [comment]
https://github.com/google/glog/commit/0b83bb203d0e6d0b3f351d76306d41bf928e72ac

**Comment by Orvid** [comment]
It's a bit messy, but it looks like we'll have to explicitly wrap `abort`, since whatever STL is in use appears to mark it as `[[noreturn]]`, which doesn't transfer to the type of the function pointer like `__attribute__((noreturn))` does. I have a change up internally that should fix the issue.
