### ISSUE TITLE
Folly fails to compile on OS X 10.9/10.10.

### ISSUE THREAD

**Issue by DomT4** [facebook/folly#451]
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++1y -g -O2 -c ClockGettimeWrappers.cpp -o ClockGettimeWrappers.o >/dev/null 2>&1
In file included from Checksum.cpp:24:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/nmmintrin.h:28:2: error: "SSE4.2 instruction set not enabled"
#error "SSE4.2 instruction set not enabled"
 ^
Checksum.cpp:47:23: error: use of undeclared identifier '_mm_crc32_u8'
      sum = (uint32_t)_mm_crc32_u8(sum, data[offset]);
                      ^
Checksum.cpp:55:11: error: use of undeclared identifier '_mm_crc32_u64'
    sum = _mm_crc32_u64(sum, *src);
          ^
Checksum.cpp:61:21: error: use of undeclared identifier '_mm_crc32_u8'
    sum = (uint32_t)_mm_crc32_u8(sum, data[offset]);
                    ^
4 errors generated.
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++1y -g -O2 -c Bits.cpp -o Bits.o >/dev/null 2>&1
make[2]: *** [Checksum.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

10.9 should be using `Apple LLVM 6.0 (clang-600.0.57)`, 10.10 should be using `Apple LLVM 7.0 (clang-700.1.81)`. No problem with 10.11, which uses `Apple LLVM version 7.3.0 (clang-703.0.31)`.

Related changes to that blob of code look to be https://github.com/facebook/folly/commit/ee6b4fce019454e4cde0355c9f084ab1284d41bf & https://github.com/facebook/folly/commit/ddd5d517e8dd65304f2fb9722e1258bdd9af5b2f. Reverting https://github.com/facebook/folly/commit/ddd5d517e8dd65304f2fb9722e1258bdd9af5b2f caused more problems than it solved:

```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++1y -g -O2 -c IPAddressV4.cpp  -fno-common -DPIC -o .libs/IPAddressV4.o
In file included from GroupVarint.cpp:17:
In file included from ./../folly/GroupVarint.h:37:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/nmmintrin.h:28:2: error: "SSE4.2 instruction set not enabled"
#error "SSE4.2 instruction set not enabled"
 ^
In file included from GroupVarint.cpp:17:
./../folly/GroupVarint.h:198:5: error: unknown type name '__m128i'
    __m128i val = _mm_loadu_si128((const __m128i*)(p+1));
    ^
./../folly/GroupVarint.h:198:42: error: unknown type name '__m128i'
    __m128i val = _mm_loadu_si128((const __m128i*)(p+1));
                                         ^
./../folly/GroupVarint.h:199:5: error: unknown type name '__m128i'
    __m128i mask =
    ^
./../folly/GroupVarint.h:200:31: error: unknown type name '__m128i'
        _mm_load_si128((const __m128i*)&detail::groupVarintSSEMasks[key * 2]);
                              ^
./../folly/GroupVarint.h:201:5: error: unknown type name '__m128i'
    __m128i r = _mm_shuffle_epi8(val, mask);
    ^
./../folly/GroupVarint.h:202:23: error: use of undeclared identifier '__m128i'
    _mm_storeu_si128((__m128i*)dest, r);
                      ^
./../folly/GroupVarint.h:202:31: error: expected expression
    _mm_storeu_si128((__m128i*)dest, r);
[snip]
```

Tested the latest tag & the current master, both problematic.

**Comment by Orvid** [comment]
Well, that's not nice of it.... It's erroring just because you don't have SSE 4.2 enabled globally, making it impossible to use the intrinsics in contexts where we've already checked at runtime that the CPU supports it, and are even marking the function that calls the intrinsics with `__attribute__((__target__("sse4.2")))` so that that particular function gets compiled with SSE 4.2 support enabled. (it also won't be inlined into any non-SSE 4.2 contexts)

Any idea what versions of upstream Clang the Apple version numbers correspond to?

**Comment by DomT4** [comment]
> Any idea what versions of upstream Clang the Apple version numbers correspond to?

Not completely sure, thanks to the slightly unusual way Apple build their Clangs. The whole output on Mavericks is `Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)` so that should be 3.5.0.

Apple dropped the `based of LLVM` bit from Yosemite, but I believe Xcode 7.2.1 shipped a LLVM based off 3.7.0 looking at [this file](https://opensource.apple.com/source/clang/clang-700.1.81/src/CMakeLists.txt).

**Comment by bingfengyiren** [comment]
I also encountered this problem。how to solve ?

**Comment by bingfengyiren** [comment]
I aslo encounter this problem . Is there any good ideas to resolve it?

**Comment by Orvid** [comment]
Other changes have gotten rid of this.

**Comment by ilovezfs** [comment]
@Orvid can you clarify what you mean?

I'm seeing this with 20170417 on OS X 10.10 Yosemite:
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c ClockGettimeWrappers.cpp  -fno-common -DPIC -o .libs/ClockGettimeWrappers.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c ClockGettimeWrappers.cpp -o ClockGettimeWrappers.o >/dev/null 2>&1
In file included from Checksum.cpp:24:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/nmmintrin.h:28:2: error: "SSE4.2 instruction set not enabled"
#error "SSE4.2 instruction set not enabled"
 ^
Checksum.cpp:47:23: error: use of undeclared identifier '_mm_crc32_u8'
      sum = (uint32_t)_mm_crc32_u8(sum, data[offset]);
                      ^
Checksum.cpp:55:20: error: use of undeclared identifier '_mm_crc32_u64'
    sum = uint32_t(_mm_crc32_u64(sum, *src));
                   ^
Checksum.cpp:61:21: error: use of undeclared identifier '_mm_crc32_u8'
    sum = (uint32_t)_mm_crc32_u8(sum, data[offset]);
                    ^
4 errors generated.
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c Bits.cpp -o Bits.o >/dev/null 2>&1
make[2]: *** [Checksum.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c Assume.cpp -o Assume.o >/dev/null 2>&1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I'm assuming you've just decided only to support >= OS X 10.11 El Capitan?

**Comment by Orvid** [comment]
Hrmmm... I'll go look, but this *should* work. Time to figure out why it isn't.

We don't actively test on anything below 10.12, so supporting it is difficult.

**Comment by ilovezfs** [comment]
@Orvid no worries. I've retained
```
  # https://github.com/facebook/folly/issues/451
  depends_on :macos => :el_capitan
```
and shipped https://github.com/Homebrew/homebrew-core/pull/12523.

**Comment by ryandesign** [comment]
Please reopen this issue. The problem has not been resolved. Folly still fails to build on OS X Yosemite (10.10) with `error: "SSE4.2 instruction set not enabled"`.
