### ISSUE TITLE
can't compile in ubuntu 14.04

### ISSUE THREAD

**Issue by zhousysu** [facebook/folly#817]
can't compile in ubuntu 14.04

```
[  1%] Building CXX object CMakeFiles/folly_base.dir/folly/File.cpp.o
In file included from /home/zhou/folly/folly/Range.h:26:0,
                 from /home/zhou/folly/folly/Conv.h:44,
                 from /home/zhou/folly/folly/Conv.cpp:16:
/home/zhou/folly/folly/portability/String.h:29:56: error: ambiguating new declaration of ‘void* memrchr(const void*, int, size_t)’
 extern "C" void* memrchr(const void* s, int c, size_t n);
                                                        ^
In file included from /usr/include/double-conversion/utils.h:32:0,
                 from /usr/include/double-conversion/double-conversion.h:31,
                 from /home/zhou/folly/folly/Conv.h:38,
                 from /home/zhou/folly/folly/Conv.cpp:16:
/usr/include/string.h:118:26: note: old declaration ‘const void* memrchr(const void*, int, size_t)’
 extern "C++" const void *memrchr (const void *__s, int __c, size_t __n)
                          ^
In file included from /home/zhou/folly/folly/Range.h:26:0,
                 from /home/zhou/folly/folly/File.h:29,
                 from /home/zhou/folly/folly/File.cpp:17:
/home/zhou/folly/folly/portability/String.h:29:56: error: ambiguating new declaration of ‘void* memrchr(const void*, int, size_t)’
 extern "C" void* memrchr(const void* s, int c, size_t n);
                                                        ^
In file included from /usr/include/c++/5/cstring:42:0,
                 from /home/zhou/folly/folly/FBString.h:53,
                 from /home/zhou/folly/folly/Demangle.h:19,
                 from /home/zhou/folly/folly/ExceptionWrapper.h:33,
                 from /home/zhou/folly/folly/File.h:26,
                 from /home/zhou/folly/folly/File.cpp:17:
/usr/include/string.h:118:26: note: old declaration ‘const void* memrchr(const void*, int, size_t)’
 extern "C++" const void *memrchr (const void *__s, int __c, size_t __n)
                          ^
cc1plus: error: unrecognized command line option ‘-Wno-inconsistent-missing-override’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/folly_base.dir/folly/Conv.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option ‘-Wno-inconsistent-missing-override’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/folly_base.dir/folly/File.cpp.o] Error 1
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jack17529** [comment]
@zhousysu don't worry We will do something

**Comment by kylezhang1983** [comment]
I had the same issue in CentOS 7 with gcc 5.1.1
/home/kylezhang/folly/folly/portability/String.h:29:56: error: ambiguating new declaration of ‘void* memrchr(const void*, int, size_t)’
 extern "C" void* memrchr(const void* s, int c, size_t n);
                                                        ^
In file included from /usr/include/double-conversion/utils.h:32:0,
                 from /usr/include/double-conversion/double-conversion.h:31,
                 from /home/kylezhang/folly/folly/Conv.h:38,
                 from /home/kylezhang/folly/folly/Conv.cpp:16:
/usr/include/string.h:114:26: note: old declaration ‘const void* memrchr(const void*, int, size_t)’
 extern "C++" const void *memrchr (const void *__s, int __c, size_t __n)
                          ^
[  4%] Building CXX object CMakeFiles/folly_base.dir/folly/FileUtil.cpp.o
In file included from /home/kylezhang/folly/folly/Range.h:26:0,
                 from /home/kylezhang/folly/folly/FileUtil.h:26,
                 from /home/kylezhang/folly/folly/FileUtil.cpp:17:
/home/kylezhang/folly/folly/portability/String.h:29:56: error: ambiguating new declaration of ‘void* memrchr(const void*, int, size_t)’
 extern "C" void* memrchr(const void* s, int c, size_t n);
                                                        ^
In file included from /usr/include/c++/5.1.1/cstring:42:0,
                 from /home/kylezhang/folly/folly/portability/Constexpr.h:22,
                 from /home/kylezhang/folly/folly/Range.h:25,
                 from /home/kylezhang/folly/folly/FileUtil.h:26,
                 from /home/kylezhang/folly/folly/FileUtil.cpp:17:
/usr/include/string.h:114:26: note: old declaration ‘const void* memrchr(const void*, int, size_t)’
 extern "C++" const void *memrchr (const void *__s, int __c, size_t __n)
                          ^
[  4%] Building CXX object CMakeFiles/folly_base.dir/folly/Format.cpp.o
cc1plus: error: unrecognized command line option ‘-Wno-inconsistent-missing-override’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/folly_base.dir/folly/Conv.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/kylezhang/folly/folly/Range.h:26:0,
                 from /home/kylezhang/folly/folly/File.h:29,
                 from /home/kylezhang/folly/folly/File.cpp:17:
/home/kylezhang/folly/folly/portability/String.h:29:56: error: ambiguating new declaration of ‘void* memrchr(const void*, int, size_t)’
 extern "C" void* memrchr(const void* s, int c, size_t n);
                                                        ^
In file included from /usr/include/c++/5.1.1/cstring:42:0,
                 from /home/kylezhang/folly/folly/FBString.h:53,
                 from /home/kylezhang/folly/folly/Demangle.h:19,
                 from /home/kylezhang/folly/folly/ExceptionWrapper.h:33,
                 from /home/kylezhang/folly/folly/File.h:26,
                 from /home/kylezhang/folly/folly/File.cpp:17:
/usr/include/string.h:114:26: note: old declaration ‘const void* memrchr(const void*, int, size_t)’
 extern "C++" const void *memrchr (const void *__s, int __c, size_t __n)
                          ^
cc1plus: error: unrecognized command line option ‘-Wno-inconsistent-missing-override’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/folly_base.dir/folly/FileUtil.cpp.o] Error 1
In file included from /home/kylezhang/folly/folly/Range.h:26:0,
                 from /home/kylezhang/folly/folly/Conv.h:44,
                 from /home/kylezhang/folly/folly/Format.h:26,
                 from /home/kylezhang/folly/folly/Format.cpp:17:
/home/kylezhang/folly/folly/portability/String.h:29:56: error: ambiguating new declaration of ‘void* memrchr(const void*, int, size_t)’
 extern "C" void* memrchr(const void* s, int c, size_t n);
                                                        ^
In file included from /usr/include/double-conversion/utils.h:32:0,
                 from /usr/include/double-conversion/double-conversion.h:31,
                 from /home/kylezhang/folly/folly/Conv.h:38,
                 from /home/kylezhang/folly/folly/Format.h:26,
                 from /home/kylezhang/folly/folly/Format.cpp:17:
/usr/include/string.h:114:26: note: old declaration ‘const void* memrchr(const void*, int, size_t)’
 extern "C++" const void *memrchr (const void *__s, int __c, size_t __n)
                          ^
cc1plus: error: unrecognized command line option ‘-Wno-inconsistent-missing-override’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/folly_base.dir/folly/File.cpp.o] Error 1
cc1plus: error: unrecognized command line option ‘-Wno-inconsistent-missing-override’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/folly_base.dir/folly/Format.cpp.o] Error 1
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
make: *** [all] Error 2

**Comment by miramar-labs** [comment]
also seeing this on RHEL7.4 GCC 7.3.0

**Comment by daniel-lucio** [comment]
For CentOS check #929
