### ISSUE TITLE
Can't compile in ubuntu 20.04 

### ISSUE THREAD

**Issue by bolunfeng** [facebook/folly#1481]
cmake -DBUILD_TESTS=ON && make 

/home/workspace/folly/folly/portability/Constexpr.h:48:29: error: ‘strlen(((const char*)(&<anonymous>)))’ is not a constant expression
   48 |   return FOLLY_DETAIL_STRLEN(s);
      |                             ^
/home/workspace/folly/folly/test/FixedStringTest.cpp:421:21: error: non-constant condition for static assertion
  421 |   static_assert(26u == tmp0.size(), "");
      |                 ~~~~^~~~~~~~~~~~~~
/home/workspace/folly/folly/test/FixedStringTest.cpp:422:19: error: non-constant condition for static assertion
  422 |   static_assert(y == tmp0, "");
      |                 ~~^~~~~~~
/home/workspace/folly/folly/test/FixedStringTest.cpp:424:21: error: non-constant condition for static assertion
  424 |   static_assert(24u == tmp1.size(), "");
      |                 ~~~~^~~~~~~~~~~~~~
/home/workspace/folly/folly/test/FixedStringTest.cpp:425:44: error: non-constant condition for static assertion
  425 |   static_assert("abcdefghijklmnopqrstuvwx" == tmp1, "");
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/workspace/folly/folly/test/FixedStringTest.cpp:427:20: error: non-constant condition for static assertion
  427 |   static_assert(2u == tmp2.size(), "");
      |                 ~~~^~~~~~~~~~~~~~
/home/workspace/folly/folly/test/FixedStringTest.cpp:428:22: error: non-constant condition for static assertion
  428 |   static_assert("ax" == tmp2, "");

**Comment by emmenlau** [comment]
@bolunfeng please do not create duplicate issues, especially not if you _know_ there is a duplicate in https://github.com/facebook/folly/issues/1444!

This helps nobody and just wastes developer time.

**Comment by bolunfeng** [comment]
I just want to remind the developers to fix this problem

**Comment by emmenlau** [comment]
@bolunfeng please don't do this. We have an older report of this problem before in https://github.com/facebook/folly/issues/1444, and a developer has already tried to help us there. Can you help reproduce the problem? If you can contribute to the problem then commend *there*.
