### ISSUE TITLE
error: ‘kDecayCmd’ was not declared in this scope

### ISSUE THREAD

**Issue by usmanxia** [facebook/folly#608]
I am getting this error when running commad "make check". I have Ubuntu 14.04 and gcc-4.9.

Please help out !!!

![image](https://user-images.githubusercontent.com/29237753/26848269-42d4ff00-4b19-11e7-873c-b4ab9d5b3288.png)

**Comment by Orvid** [comment]
This was caused by https://github.com/facebook/folly/commit/cd201c86411f960e6e63c8222a334cea5ed67768. I'm working on a fix now.

As a temporary workaround, remove these two lines and it should compile again:
https://github.com/facebook/folly/blob/master/folly/test/MallctlHelperTest.cpp#L28
https://github.com/facebook/folly/blob/master/folly/test/MallctlHelperTest.cpp#L36


`kDecayCmd` is incorrectly getting guarded to only be defined when JEMalloc is enabled.

**Comment by usmanxia** [comment]
Thank u for apt reply. Lemme try that

**Comment by usmanxia** [comment]
Done, Thank you
