### ISSUE TITLE
Build failure with Boost.Context 1.61

### ISSUE THREAD

**Issue by pefoley2** [facebook/folly#413]
When building hhvm against boost 1.61, folly fails to compile with the below error.
According to http://www.boost.org/users/history/version_1_61_0.html, fcontext_t is no longer part of the public api.

[  5%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/experimental/fibers/Baton.cpp.o
In file included from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Fiber.h:26:0,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Baton-inl.h:16,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.h:191,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.cpp:16:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:38:41: error: ‘fcontext_t’ in namespace ‘boost::context’ does not name a type
   using ContextStruct = boost::context::fcontext_t;
                                         ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:56:3: error: ‘ContextStruct’ does not name a type
   ContextStruct context_;
   ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:64:41: error: ‘folly::fibers::FContext::ContextStruct’ has not been declared
   jumpContext(FContext\* oldC, FContext::ContextStruct\* newC, intptr_t p);
                                         ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:66:25: error: ‘folly::fibers::FContext::ContextStruct’ has not been declared
   jumpContext(FContext::ContextStruct\* oldC, FContext\* newC, intptr_t p);
                         ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:72:39: error: ‘folly::fibers::FContext::ContextStruct’ has not been declared
 jumpContext(FContext\* oldC, FContext::ContextStruct\* newC, intptr_t p) {
                                       ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h: In function ‘intptr_t folly::fibers::jumpContext(folly::fibers::FContext_, int_, intptr_t)’:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:74:10: error: ‘jump_fcontext’ is not a member of ‘boost::context’
   return boost::context::jump_fcontext(&oldC->context_, _newC, p);
          ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:74:10: note: suggested alternative:
In file included from /usr/include/boost/context/detail/exception.hpp:12:0,
                 from /usr/include/boost/context/execution_context_v2.hpp:28,
                 from /usr/include/boost/context/execution_context.hpp:13,
                 from /usr/include/boost/context/all.hpp:7,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:18,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Fiber.h:26,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Baton-inl.h:16,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.h:191,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.cpp:16:
/usr/include/boost/context/detail/fcontext.hpp:31:35: note:   ‘boost::context::detail::jump_fcontext’
 transfer_t BOOST_CONTEXT_CALLDECL jump_fcontext( fcontext_t const to, void \* vp);
                                   ^
In file included from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Fiber.h:26:0,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Baton-inl.h:16,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.h:191,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.cpp:16:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:74:47: error: ‘struct folly::fibers::FContext’ has no member named ‘context_’
   return boost::context::jump_fcontext(&oldC->context_, *newC, p);
                                               ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h: At global scope:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:23: error: ‘folly::fibers::jumpContext’ declared as an ‘inline’ variable
 jumpContext(FContext::ContextStruct_ oldC, FContext\* newC, intptr_t p) {
                       ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:23: error: ‘intptr_t folly::fibers::jumpContext’ redeclared as different kind of symbol
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:66:3: note: previous declaration ‘intptr_t folly::fibers::jumpContext(int_, folly::fibers::FContext_, intptr_t)’
   jumpContext(FContext::ContextStruct\* oldC, FContext\* newC, intptr_t p);
   ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:13: error: ‘ContextStruct’ is not a member of ‘folly::fibers::FContext’
 jumpContext(FContext::ContextStruct\* oldC, FContext\* newC, intptr_t p) {
             ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:38: error: ‘oldC’ was not declared in this scope
 jumpContext(FContext::ContextStruct\* oldC, FContext\* newC, intptr_t p) {
                                      ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:52: error: expected primary-expression before ‘_’ token
 jumpContext(FContext::ContextStruct_ oldC, FContext\* newC, intptr_t p) {
                                                    ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:54: error: ‘newC’ was not declared in this scope
 jumpContext(FContext::ContextStruct\* oldC, FContext\* newC, intptr_t p) {
                                                      ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:83:69: error: expected primary-expression before ‘p’
 jumpContext(FContext::ContextStruct\* oldC, FContext\* newC, intptr_t p) {
                                                                     ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h: In function ‘folly::fibers::FContext folly::fibers::makeContext(void_, size_t, void (_)(intptr_t))’:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:98:7: error: ‘struct folly::fibers::FContext’ has no member named ‘context_’
   res.context_ = boost::context::make_fcontext(res.stackBase_, stackSize, fn);
       ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:98:18: error: ‘make_fcontext’ is not a member of ‘boost::context’
   res.context_ = boost::context::make_fcontext(res.stackBase_, stackSize, fn);
                  ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:98:18: note: suggested alternative:
In file included from /usr/include/boost/context/detail/exception.hpp:12:0,
                 from /usr/include/boost/context/execution_context_v2.hpp:28,
                 from /usr/include/boost/context/execution_context.hpp:13,
                 from /usr/include/boost/context/all.hpp:7,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/BoostContextCompatibility.h:18,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Fiber.h:26,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Baton-inl.h:16,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.h:191,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.cpp:16:
/usr/include/boost/context/detail/fcontext.hpp:33:35: note:   ‘boost::context::detail::make_fcontext’
 fcontext_t BOOST_CONTEXT_CALLDECL make_fcontext( void \* sp, std::size_t size, void (\* fn)( transfer_t) );
                                   ^
In file included from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Baton-inl.h:17:0,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.h:191,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.cpp:16:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager.h: At global scope:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager.h:370:13: error: ‘ContextStruct’ in ‘struct folly::fibers::FContext’ does not name a type
   FContext::ContextStruct mainContext_; /*_< stores loop function context */
             ^
In file included from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager.h:565:0,
                 from /home/peter/hhvm/third-party/folly/folly/experimental/fibers/Baton-inl.h:17,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.h:191,
                 from /home/peter/hhvm/third-party/folly/src/folly/experimental/fibers/Baton.cpp:16:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager-inl.h: In member function ‘intptr_t folly::fibers::FiberManager::activateFiber(folly::fibers::Fiber_)’:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager-inl.h:70:23: error: ‘mainContext_’ was not declared in this scope
   return jumpContext(&mainContext_, &fiber->fcontext_, fiber->data_);
                       ^
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager-inl.h: In member function ‘intptr_t folly::fibers::FiberManager::deactivateFiber(folly::fibers::Fiber_)’:
/home/peter/hhvm/third-party/folly/folly/experimental/fibers/FiberManager-inl.h:81:42: error: ‘mainContext_’ was not declared in this scope
   return jumpContext(&fiber->fcontext_, &mainContext_, 0);
                                          ^
third-party/folly/CMakeFiles/folly.dir/build.make:1166: recipe for target 'third-party/folly/CMakeFiles/folly.dir/src/folly/experimental/fibers/Baton.cpp.o' failed
make[2]: *_\* [third-party/folly/CMakeFiles/folly.dir/src/folly/experimental/fibers/Baton.cpp.o] Error 1
CMakeFiles/Makefile2:354: recipe for target 'third-party/folly/CMakeFiles/folly.dir/all' failed
make[1]: **\* [third-party/folly/CMakeFiles/folly.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by rleigh-dundee** [comment]
Has anyone had a chance to take a look at this yet?  It's a blocker for updating boost in homebrew.

**Comment by Orvid** [comment]
I looked at it some, and the API is still there, but it's been moved to `detail` and there are also some moderate changes in the API. I don't know enough about our current use of it in futures to be able to make the changes required.

**Comment by bhamiltoncx** [comment]
This is definitely a blocking problem.

Unless someone complains otherwise, I'm just going to disable compiling or installing the Folly Fibers library if Boost.Detail isn't working.

**Comment by bhamiltoncx** [comment]
Fix should come later today. Sorry for the pain, and thanks for reporting.

**Comment by Orvid** [comment]
This still needs to be open as fibers still needs to be updated to work with 1.61.

**Comment by bhamiltoncx** [comment]
Orvid, we should track that work separately. The library now builds (but
without Fibers) with both 1.60 and 1.61.
2016年6月10日(金) 16:49 Orvid King <notifications@github.com>:

**Comment by doctaweeks** [comment]
This still need to be open because there is still a build failure on some platforms when futures uses fibers by default. (folly/futures/Future-inl.h:31)

**Comment by olk** [comment]
Because folly is a C++11 library you could use execution_context (from boost.context) instead.
Otherwise, if you insist the fcontext-API (now in namespace detail) you should note, that:
1) context entered first time: the suspended context is passed as member of struct transfer_t to the context-function
2) context was already suspended before: in resumed context jump_fcontext() returns struct transfer_t with suspended context

**Comment by zcourts** [comment]
Since I'm using folly maily for fibers disabling/deferring isn't an option so downgraded boost and patched `folly/build/bootstrap-osx-homebrew.sh`

```
diff --git a/folly/build/bootstrap-osx-homebrew.sh b/folly/build/bootstrap-osx-homebrew.sh
index c7c350c..8c5b9ae 100755
--- a/folly/build/bootstrap-osx-homebrew.sh
+++ b/folly/build/bootstrap-osx-homebrew.sh
@@ -9,21 +9,21 @@ BASE_DIR="$(cd "$(dirname -- "$0")"/.. ; pwd)"  # folly/folly
 cd "$BASE_DIR"

 brewget() {
-    brew install $@ || brew upgrade $@
+    brew install $@ #|| brew upgrade $@
 }

 # tool dependencies: autotools and scons (for double-conversion)
 brewget autoconf automake libtool

 # dependencies
-brewget glog gflags boost libevent double-conversion
+brewget glog gflags libevent double-conversion #homebrew/versions/boost155

 autoreconf -i
 ./configure

 pushd test
-test -e gtest-1.7.0.zip || {
-    curl -O https://googletest.googlecode.com/files/gtest-1.7.0.zip
-    unzip gtest-1.7.0.zip
+test -e release-1.7.0.zip || {
+    curl -O https://github.com/google/googletest/archive/release-1.7.0.zip
+    unzip release-1.7.0.zip
 }
 popd
```
Downgraded to 155 but 159 may work, as well (haven't tested).

For anyone else building from source instead of the off the shelf brew version, If you don't already have openssl or libressl then install them:
`brew install libressl or openssl`

then to have the paths picked up, export `LIBS`

Possibly swap out with libressl

`export LIBS='-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib'`

If the flag isn't picked up i.e. it fails to compile saying it can't find an openssl header then 
`vim Makefile`
and find `CPPFLAGS =` 

which may or may not be empty and add the openssl path to it so we get 
`CPPFLAGS = -I/usr/local/opt/openssl/include`

Then your standard 
`make && make install`

**Comment by Orvid** [comment]
Boost >= 1.61 is now supported via https://github.com/facebook/folly/commit/0b894c40e54e645bf1da19bcb9a28147ee2ce2b4.

**Comment by wrigleyster** [comment]
This fix was broken/undone in 3433e03

**Comment by Orvid** [comment]
Re-fixed (correctly this time!) in https://github.com/facebook/folly/commit/823ecf8917d7f0534ed02b8d38bfc966cb0fd7b6.
