### PR TITLE
Uncomment insert call in FBStringTest.cpp

### PR DESCRIPTION
**Pull request by JoeLoser**
Summary:
- Previous versions of GCC apparently cause a bug to happen with the two
  `insert` calls that are commented out.
- Uncomment the `insert` calls which works fine with GCC 5.1.

### CODE REVIEW

**Comment by yfeldblum** [comment]
This seems to fail with recent clang + libstdc++.

```
folly/test/FBStringTest.cpp:483:7: error: no viable overloaded '='
  res = test.insert(test.begin() + pos, il);
  ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
folly/test/FBStringTest.cpp:1146:3: note: in instantiation of function template specialization 'clause11_21_4_6_4<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' requested here
  TEST_CLAUSE(21_4_6_4);
  ^
folly/test/FBStringTest.cpp:1111:5: note: expanded from macro 'TEST_CLAUSE'
    clause11_##x<std::string>,     \
    ^
<scratch space>:195:1: note: expanded from here
clause11_21_4_6_4
^
libgcc/include/c++/7.3.0/bits/stl_iterator.h:761:11: note: candidate function (the implicit copy assignment operator) not viable: cannot convert argument of incomplete type 'void' to 'const __gnu_cxx::__normal_iterator<char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' for 1st argument
    class __normal_iterator
          ^
libgcc/include/c++/7.3.0/bits/stl_iterator.h:761:11: note: candidate function (the implicit move assignment operator) not viable: cannot convert argument of incomplete type 'void' to '__gnu_cxx::__normal_iterator<char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' for 1st argument
```

**Comment by JoeLoser** [comment]
I see. It seems likely to be a recent `libstdc++` problem then, since:

1. It works with GCC 5.1 and `libstdc++` per the CI passing
2. Tested locally with Clang 7.0.1 and `libc++` which also passes.

I'll simply close this PR for now, unless you feel strongly about updating the comment to clarify it's a `libstdc++` runtime issue.

**Comment by yfeldblum** [comment]
I don't feel strongly, but thank you.
