### ISSUE TITLE
v2022.02.21.00 build failed with GCC (missing `#include`)

### ISSUE THREAD

**Issue by carlocab** [facebook/folly#1720]
Building from the `v2022.02.21.00` tag fails with GCC 11 (installed via Homebrew) on Ubuntu 16.04, with the error:
```
  /tmp/folly-20220221-9776-5ibh2u/folly-2022.02.21.00/folly/Traits.h:873:39: error: 'uint8_t' is not a member of 'std'; did you mean 'wint_t'?
    873 | struct uint_bits_t_<8> : type_t_<std::uint8_t> {};
        |                                       ^~~~~~~
        |                                       wint_t
```
Complete build logs available [here](https://github.com/Homebrew/homebrew-core/runs/5271863980?check_suite_focus=true), and the error starts [here](https://github.com/Homebrew/homebrew-core/runs/5271863980?check_suite_focus=true#step:7:199).

This failure seems specific to GCC, as our builds on macOS (10.15, 11, 12, both Intel and ARM where applicable) using Clang succeeded.

It seems likely due to a missing `#include` directive in 76b10a07977ade1e3c62338e6b06fe5ba38d1b1d. Indeed, adding `-include cstdint` to `CXXFLAGS` allows the build to succeed.
