### ISSUE TITLE
build error with gcc 7.4 ubuntu18.04

### ISSUE THREAD

**Issue by silveric10** [facebook/folly#1136]
Hi all, I got those errors when I build with gcc 7.04
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/Conv.cpp.o
In file included from /home/yy/openr/build/deps/folly/folly/FBString.h:59:0,
                 from /home/yy/openr/build/deps/folly/folly/Demangle.h:19,
                 from /home/yy/openr/build/deps/folly/folly/Conv.h:40,
                 from /home/yy/openr/build/deps/folly/folly/Conv.cpp:16:
/home/yy/openr/build/deps/folly/folly/hash/Hash.h:709:8: error: redefinition of ‘struct std::hash<__int128>’
 struct hash<__int128> : folly::detail::integral_hasher<__int128> {};
        ^~~~~~~~~~~~~~
In file included from /usr/include/c++/7/string_view:43:0,
                 from /usr/include/c++/7/bits/basic_string.h:48,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /home/yy/openr/build/deps/folly/folly/Conv.h:32,
                 from /home/yy/openr/build/deps/folly/folly/Conv.cpp:16:
/usr/include/c++/7/bits/functional_hash.h:169:3: note: previous definition of ‘struct std::hash<__int128>’
   _Cxx_hashtable_define_trivial_hash(__GLIBCXX_TYPE_INT_N_0)
   ^
In file included from /home/yy/openr/build/deps/folly/folly/FBString.h:59:0,
                 from /home/yy/openr/build/deps/folly/folly/Demangle.h:19,
                 from /home/yy/openr/build/deps/folly/folly/Conv.h:40,
                 from /home/yy/openr/build/deps/folly/folly/Conv.cpp:16:
/home/yy/openr/build/deps/folly/folly/hash/Hash.h:712:8: error: redefinition of ‘struct std::hash<__int128 unsigned>’
 struct hash<unsigned __int128>
        ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/string_view:43:0,
                 from /usr/include/c++/7/bits/basic_string.h:48,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /home/yy/openr/build/deps/folly/folly/Conv.h:32,
                 from /home/yy/openr/build/deps/folly/folly/Conv.cpp:16:
/usr/include/c++/7/bits/functional_hash.h:170:3: note: previous definition of ‘struct std::hash<__int128 unsigned>’
   _Cxx_hashtable_define_trivial_hash(__GLIBCXX_TYPE_INT_N_0 unsigned)
   ^
CMakeFiles/folly_base.dir/build.make:110: recipe for target 'CMakeFiles/folly_base.dir/folly/Conv.cpp.o' failed
make[2]: *** [CMakeFiles/folly_base.dir/folly/Conv.cpp.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/folly_base.dir/all' failed
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

Can you help? Thanks

**Comment by suspend0** [comment]
the conflicting block is guarded by `#if FOLLY_SUPPLY_MISSING_INT128_TRAITS`, which is defined by `folly/folly-config.h`, which (I think) is output by folly's build.

I've you've upgraded your compiler since you last built folly, of the compiler you're using now different from the one built folly, then those configuration values might be incorrect.

(I had this issue when building folly library with gcc5 and my app with gcc7)

**Comment by silveric10** [comment]
> the conflicting block is guarded by #if FOLLY_SUPPLY_MISSING_INT128_TRAITS, which is defined by folly/folly-config.h, which (I think) is output by folly's build.
> I've you've upgraded your compiler since you last built folly, of the compiler you're using now different from the one built folly, then those configuration values might be incorrect.
> (I had this issue when building folly library with gcc5 and my app with gcc7)

Thank you, I will clean first and try again.

**Comment by silveric10** [comment]
> the conflicting block is guarded by #if FOLLY_SUPPLY_MISSING_INT128_TRAITS, which is defined by folly/folly-config.h, which (I think) is output by folly's build.
> I've you've upgraded your compiler since you last built folly, of the compiler you're using now different from the one built folly, then those configuration values might be incorrect.
> (I had this issue when building folly library with gcc5 and my app with gcc7)

Hello. Do you know how to make folly with c++14? I have gcc7 but it still has those issues:
 40%] Building CXX object thrift/lib/cpp/CMakeFiles/thrift-core.dir/Thrift.cpp.o
In file included from /usr/local/include/folly/Range.h:22:0,
                 from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.h:20,
                 from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.cpp:21:
/usr/local/include/folly/Portability.h:22:1: error: static assertion failed: __cplusplus >= 201402L
 static_assert(__cplusplus >= 201402L, "__cplusplus >= 201402L");
 ^~~~~~~~~~~~~
In file included from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.h:20:0,
                 from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.cpp:21:
/usr/local/include/folly/Range.h:522:12: error: ‘std::enable_if_t’ has not been declared
       std::enable_if_t<
            ^~~~~~~~~~~
/usr/local/include/folly/Range.h:522:23: error: expected ‘>’ before ‘<’ token

**Comment by Ansudeen** [comment]
Hi, I'm getting the same issue with devttolset-9.0 with c++17. 

/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/functional_hash.h:264:12: error: redefinition of ‘struct std::hash<long int>’
  264 |     struct hash<nullptr_t> : public __hash_base<size_t, nullptr_t>
      |            ^~~~~~~~~~~~~~~
/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/functional_hash.h:156:3: note: previous definition of ‘struct std::hash<long int>’
  156 |   _Cxx_hashtable_define_trivial_hash(long)

any suggestions?
