### ISSUE TITLE
Folly fails to compile using gcc-6.3.1 on CentOS-7

### ISSUE THREAD

**Issue by cgurps** [facebook/folly#1344]
Hello everyone,

I'm trying to compile folly on centos-7 using `gcc-6.3.1` and I get the following error:
```
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:52:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.h:19,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h: In instantiation of ‘class std::basic_string<char, std::char_traits<char>, folly::reentrant_allocator<char> >’:
/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/ElfCache.h:62:10:   required from here
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2616:63: error: no class template named ‘rebind’ in ‘class folly::reentrant_allocator<char>’
       typedef typename _Alloc::template rebind<_CharT>::other _CharT_alloc_type;
                                                               ^~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2629:68: error: no class template named ‘rebind’ in ‘class folly::reentrant_allocator<char>’
       typedef __gnu_cxx::__normal_iterator<pointer, basic_string>  iterator;
                                                                    ^~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2631:61: error: no class template named ‘rebind’ in ‘class folly::reentrant_allocator<char>’
                                                             const_iterator;
                                                             ^~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2632:53: error: no class template named ‘rebind’ in ‘class folly::reentrant_allocator<char>’
       typedef std::reverse_iterator<const_iterator> const_reverse_iterator;
                                                     ^~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2633:52: error: no class template named ‘rebind’ in ‘class folly::reentrant_allocator<char>’
       typedef std::reverse_iterator<iterator>      reverse_iterator;
                                                    ^~~~~~~~~~~~~~~~
In file included from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/Symbolizer.h:32:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:22:
/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/ElfCache.h: In constructor ‘folly::symbolizer::SignalSafeElfCache::Entry::Entry(folly::StringPiece, folly::reentrant_allocator<char>)’:
/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/ElfCache.h:68:52: error: no matching function for call to ‘std::basic_string<char, std::char_traits<char>, folly::reentrant_allocator<char> >::basic_string(<brace-enclosed initializer list>)’
           file{std::allocate_shared<ElfFile>(alloc)} {}
                                                    ^
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:53:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.h:19,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:667:5: note: candidate: template<class _InputIterator> std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&)
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:667:5: note:   template argument deduction/substitution failed:
In file included from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/Symbolizer.h:32:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:22:
/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/ElfCache.h:68:52: note:   deduced conflicting types for parameter ‘_InputIterator’ (‘const char*’ and ‘long unsigned int’)
           file{std::allocate_shared<ElfFile>(alloc)} {}
                                                    ^
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:53:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.h:19,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:674:5: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::initializer_list<_Tp>, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:674:5: note:   candidate expects 2 arguments, 3 provided
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:52:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.h:19,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3042:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]
       basic_string(basic_string&& __str)
       ^~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3042:7: note:   candidate expects 1 argument, 3 provided
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:53:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.h:19,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:652:5: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:652:5: note:   candidate expects 2 arguments, 3 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:609:5: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:609:5: note:   candidate expects 1 argument, 3 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:617:5: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:617:5: note:   candidate expects 1 argument, 3 provided
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:52:0,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.h:19,
                 from /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2972:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]
       basic_string()
       ^~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2972:7: note:   candidate expects 0 arguments, 3 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h: In instantiation of ‘struct std::basic_string<char, std::char_traits<char>, folly::reentrant_allocator<char> >::_Rep’:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3077:19:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::~basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]’
/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/ElfCache.h:68:52:   required from here
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2660:56: error: no class template named ‘rebind’ in ‘class folly::reentrant_allocator<char>’
  typedef typename _Alloc::template rebind<char>::other _Raw_bytes_alloc;
                                                        ^~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h: In instantiation of ‘int std::basic_string<_CharT, _Traits, _Alloc>::compare(const std::basic_string<_CharT, _Traits, _Alloc>&) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]’:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:5153:35:   required from ‘bool std::operator<(const std::basic_string<_CharT, _Traits, _Alloc>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]’
/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/experimental/symbolizer/ElfCache.h:73:25:   required from here
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:4799:20: error: ‘_S_compare’ was not declared in this scope
    __r = _S_compare(__size, __osize);
```
which indicates that the `folly::reentrant_allocator` doesn't provide a `rebind` method (which is indeed the case looking at the code). The standard says that "rebind is only optional (provided by `std::allocator_traits`) if this allocator is a template of the form `SomeAllocator<T, Args>`, where Args is zero or more additional template type parameters." (see [this](https://en.cppreference.com/w/cpp/named_req/Allocator#cite_note-2)).

I was wondering if that's intended or if it is an error? Note that I've not found any similar issues thus this new one.

Here's also the cmake output:
```
-- The CXX compiler identification is GNU 6.3.1
-- The C compiler identification is GNU 6.3.1
-- Check for working CXX compiler: /bin/ccache
-- Check for working CXX compiler: /bin/ccache -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /bin/ccache
-- Check for working C compiler: /bin/ccache -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Boost: /film/tools/packages/AL_boost/1.66.0/include (found suitable version "1.66.0", minimum required is "1.51.0") found components: context filesystem program_options regex system thread chrono date_time atomic 
-- Found DOUBLE_CONVERSION: /home/users/thomascai/packages/folly/3.30.0/lib64/libdouble-conversion.a  
-- Found double-conversion: /home/users/thomascai/packages/folly/3.30.0/lib64/libdouble-conversion.a
-- Found gflags from package config /home/users/thomascai/packages/folly/3.30.0/lib/cmake/gflags/gflags-config.cmake
-- Found glog: /usr/lib64/libglog.so  
-- Found libevent: /usr/lib64/libevent.so
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
-- Looking for ASN1_TIME_diff
-- Looking for ASN1_TIME_diff - found
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so - found
-- Found LibLZMA: /usr/lib64/liblzma.so (found version "5.2.2") 
-- Found LZ4: /usr/lib64/liblz4.so  
-- Found LZ4: /usr/lib64/liblz4.so
-- Found ZSTD: /usr/lib64/libzstd.so  
-- Found Zstd: /usr/lib64/libzstd.so
-- Found SNAPPY: /usr/lib64/libsnappy.so  
-- Found LIBDWARF: /usr/lib64/libdwarf.so  
-- Found LIBIBERTY: /usr/lib64/libiberty.a  
-- Found LIBAIO: /usr/lib64/libaio.so  
-- Could NOT find LIBURING (missing: LIBURING_LIBRARY LIBURING_INCLUDE_DIR) 
-- Found LIBSODIUM: /usr/lib64/libsodium.so  
-- Found Libsodium: /usr/lib64/libsodium.so
-- Looking for C++ include elf.h
-- Looking for C++ include elf.h - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Setting FOLLY_USE_SYMBOLIZER: ON
-- Performing Test FOLLY_CPP_ATOMIC_BUILTIN
-- Performing Test FOLLY_CPP_ATOMIC_BUILTIN - Success
-- Looking for C++ include jemalloc/jemalloc.h
-- Looking for C++ include jemalloc/jemalloc.h - not found
-- Performing Test COMPILER_HAS_UNKNOWN_WARNING_OPTION
-- Performing Test COMPILER_HAS_UNKNOWN_WARNING_OPTION - Failed
-- Performing Test COMPILER_HAS_W_SHADOW_LOCAL
-- Performing Test COMPILER_HAS_W_SHADOW_LOCAL - Failed
-- Performing Test COMPILER_HAS_W_SHADOW_COMPATIBLE_LOCAL
-- Performing Test COMPILER_HAS_W_SHADOW_COMPATIBLE_LOCAL - Failed
-- Performing Test COMPILER_HAS_W_NOEXCEPT_TYPE
-- Performing Test COMPILER_HAS_W_NOEXCEPT_TYPE - Failed
-- Performing Test COMPILER_HAS_W_NULLABILITY_COMPLETENESS
-- Performing Test COMPILER_HAS_W_NULLABILITY_COMPLETENESS - Failed
-- Performing Test COMPILER_HAS_W_INCONSISTENT_MISSING_OVERRIDE
-- Performing Test COMPILER_HAS_W_INCONSISTENT_MISSING_OVERRIDE - Failed
-- Performing Test COMPILER_HAS_F_ALIGNED_NEW
-- Performing Test COMPILER_HAS_F_ALIGNED_NEW - Failed
-- Performing Test COMPILER_HAS_F_OPENMP
-- Performing Test COMPILER_HAS_F_OPENMP - Success
-- Looking for pthread_atfork
-- Looking for pthread_atfork - found
-- Looking for memrchr
-- Looking for memrchr - found
-- Looking for accept4
-- Looking for accept4 - found
-- Looking for getrandom
-- Looking for getrandom - not found
-- Looking for preadv
-- Looking for preadv - found
-- Looking for pwritev
-- Looking for pwritev - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for pipe2
-- Looking for pipe2 - found
-- Looking for sendmmsg
-- Looking for sendmmsg - found
-- Looking for recvmmsg
-- Looking for recvmmsg - found
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - found
-- Performing Test FOLLY_HAVE_IFUNC
-- Performing Test FOLLY_HAVE_IFUNC - Success
-- Performing Test FOLLY_HAVE_STD__IS_TRIVIALLY_COPYABLE
-- Performing Test FOLLY_HAVE_STD__IS_TRIVIALLY_COPYABLE - Success
-- Performing Test FOLLY_HAVE_UNALIGNED_ACCESS
-- Performing Test FOLLY_HAVE_UNALIGNED_ACCESS - Success
-- Performing Test FOLLY_HAVE_VLA
-- Performing Test FOLLY_HAVE_VLA - Success
-- Performing Test FOLLY_HAVE_WEAK_SYMBOLS
-- Performing Test FOLLY_HAVE_WEAK_SYMBOLS - Success
-- Performing Test FOLLY_HAVE_LINUX_VDSO
-- Performing Test FOLLY_HAVE_LINUX_VDSO - Success
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of __int128
-- Check size of __int128 - done
-- Performing Test HAVE_INT128_TRAITS
-- Performing Test HAVE_INT128_TRAITS - Success
-- Performing Test FOLLY_HAVE_WCHAR_SUPPORT
-- Performing Test FOLLY_HAVE_WCHAR_SUPPORT - Success
-- Performing Test FOLLY_HAVE_EXTRANDOM_SFMT19937
-- Performing Test FOLLY_HAVE_EXTRANDOM_SFMT19937 - Success
-- Performing Test FOLLY_USE_LIBCPP
-- Performing Test FOLLY_USE_LIBCPP - Failed
-- Performing Test FOLLY_USE_LIBSTDCPP
-- Performing Test FOLLY_USE_LIBSTDCPP - Success
-- Performing Test HAVE_VSNPRINTF_ERRORS
-- Performing Test HAVE_VSNPRINTF_ERRORS - Success
-- Performing Test GFLAGS_NAMESPACE_IS_GFLAGS
-- Performing Test GFLAGS_NAMESPACE_IS_GFLAGS - Success
-- arch  does not match x86_64, skipping setting SSE2/AVX2 compile flags for LtHash SIMD code
-- Performing Test COMPILER_HAS_M_PCLMUL
-- Performing Test COMPILER_HAS_M_PCLMUL - Success
-- compiler has flag pclmul, setting compile flag for /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/hash/detail/ChecksumDetail.cpp;/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/hash/detail/Crc32CombineDetail.cpp;/scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly/folly/hash/detail/Crc32cDetail.cpp
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/thomascai/git/rezExternalPackages/folly/3.30.0/build/folly-prefix/src/folly-build
```

**Comment by yanke1311** [comment]
I met the same problem, if you have had the solution?

**Comment by cgurps** [comment]
No I was waiting for a response!

**Comment by seven7777777** [comment]
Waitting for a solution....

**Comment by yanke1311** [comment]
my college helped change some source code , and it worked

**Comment by boringuy** [comment]
I am having the same issue with CentOS 7.4 and devtoolset-7 (c++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)) and have tracked down to this commit that introduced this error:

commit 88cc7c9355396e1f2104f998f8e5946a16a91055 (HEAD)
Author: Yedidya Feldblum <yfeldblum@fb.com>
Date:   Mon Feb 10 00:20:03 2020 -0800

    Revise SignalSafeElfCache to allocate with mmap

This is right after v2020.02.10.00. So, that release still works fine. The latest release tag (v2020.07.13.00) has similar error but slight different:

/opt/rh/devtoolset-7/root/usr/bin/c++  -DFMT_LOCALE -DFOLLY_XLOG_STRIP_PREFIXES=\"/usr/local/core-cpp/third_party/folly:/usr/local/core-cpp/third_party/folly/_build\" -DGFLAGS_IS_A_DLL=0 -D_GNU_SOURCE -D_REENTRANT -I/usr/local/core-cpp/third_party/folly -I/usr/local/core-cpp/third_party/folly/_build -I/usr/include/libdwarf  -g -std=gnu++1z -finput-charset=UTF-8 -fsigned-char -Wall -Wno-deprecated -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused -Wunused-label -Wunused-result -Wshadow-compatible-local -Wno-noexcept-type -faligned-new -fopenmp -o CMakeFiles/folly_base.dir/folly/detail/SingletonStackTrace.cpp.o -c /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.cpp
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:53:0,
                 from /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.h:19,
                 from /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]’:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:5033:30:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]’
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:5054:27:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]’
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:657:31:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/local/core-cpp/third_party/folly/folly/experimental/symbolizer/ElfCache.h:62:52:   required from here
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:568:31: error: no matching function for call to ‘folly::reentrant_allocator<char>::reentrant_allocator()’
  if (__beg == __end && __a == _Alloc())
                               ^~~~~~~~
In file included from /usr/local/core-cpp/third_party/folly/folly/experimental/symbolizer/ElfCache.h:30:0,
                 from /usr/local/core-cpp/third_party/folly/folly/experimental/symbolizer/Symbolizer.h:32,
                 from /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.cpp:22:
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:134:18: note: candidate: folly::detail::reentrant_allocator_base_non_void<T>::reentrant_allocator_base_non_void(const folly::detail::reentrant_allocator_base&) [with T = char]
   /* implicit */ reentrant_allocator_base_non_void(
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   inherited here
   using base::base;
               ^~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   candidate expects 1 argument, 0 provided
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:62:12: note: candidate: folly::detail::reentrant_allocator_base::reentrant_allocator_base(const folly::reentrant_allocator_options&)
   explicit reentrant_allocator_base(
            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   inherited here
   using base::base;
               ^~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   candidate expects 1 argument, 0 provided
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:127:7: note: candidate: folly::detail::reentrant_allocator_base_non_void<char>::reentrant_allocator_base_non_void(const folly::detail::reentrant_allocator_base_non_void<char>&)
 class reentrant_allocator_base_non_void : public reentrant_allocator_base {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   inherited here
   using base::base;
               ^~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   candidate expects 1 argument, 0 provided
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:127:7: note: candidate: folly::detail::reentrant_allocator_base_non_void<char>::reentrant_allocator_base_non_void(folly::detail::reentrant_allocator_base_non_void<char>&&)
 class reentrant_allocator_base_non_void : public reentrant_allocator_base {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   inherited here
   using base::base;
               ^~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:199:15: note:   candidate expects 1 argument, 0 provided
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:202:18: note: candidate: template<class U, typename std::enable_if<(! std::is_same<T, char>::value), int>::type <anonymous> > folly::reentrant_allocator<T>::reentrant_allocator(const folly::reentrant_allocator<U>&)
   /* implicit */ reentrant_allocator(
                  ^~~~~~~~~~~~~~~~~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:202:18: note:   template argument deduction/substitution failed:
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:53:0,
                 from /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.h:19,
                 from /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.cpp:17:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:568:31: note:   candidate expects 1 argument, 0 provided
  if (__beg == __end && __a == _Alloc())
                               ^~~~~~~~
In file included from /usr/local/core-cpp/third_party/folly/folly/experimental/symbolizer/ElfCache.h:30:0,
                 from /usr/local/core-cpp/third_party/folly/folly/experimental/symbolizer/Symbolizer.h:32,
                 from /usr/local/core-cpp/third_party/folly/folly/detail/SingletonStackTrace.cpp:22:
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:178:7: note: candidate: folly::reentrant_allocator<char>::reentrant_allocator(const folly::reentrant_allocator<char>&)
 class reentrant_allocator : private detail::reentrant_allocator_base_for<T> {
       ^~~~~~~~~~~~~~~~~~~
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:178:7: note:   candidate expects 1 argument, 0 provided
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:178:7: note: candidate: folly::reentrant_allocator<char>::reentrant_allocator(folly::reentrant_allocator<char>&&)
/usr/local/core-cpp/third_party/folly/folly/memory/ReentrantAllocator.h:178:7: note:   candidate expects 1 argument, 0 provided
make[2]: *** [CMakeFiles/folly_base.dir/build.make:648: CMakeFiles/folly_base.dir/folly/detail/SingletonStackTrace.cpp.o] Error 1
make[2]: Leaving directory '/usr/local/core-cpp/third_party/folly/_build'
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/folly_base.dir/all] Error 2
make[1]: Leaving directory '/usr/local/core-cpp/third_party/folly/_build'

**Comment by boringuy** [comment]
So, it looks like the issue posted by OP is "fixed" in this commit:
commit b14c9ea61cb43665eb6ef6aa600f745483f1fe97 (tag: v2020.05.18.00)
Author: Yedidya Feldblum <yfeldblum@fb.com>
Date:   Sun May 17 10:39:57 2020 -0700

    Fill reentrant_allocator member types and functions

    Summary:
    [Folly] Fill `reentrant_allocator` member types and functions for situations which fail to indirect via `std::allocator_traits`, such as the former implementation of libstdc++ `std::basic_string`.

    May help to address https://github.com/facebook/fboss/issues/86.

    Differential Revision: D21608091

    fbshipit-source-id: 020ac3bd37b27a08dd7c8113a77979d0ba21a8fc

That's the v2020.05.18.00 release but it introduced the new error that I posted and still broken in latest v2020.07.13.00

**Comment by yfeldblum** [comment]
Looks like the latest compile error is here:

```
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:568:31: note: candidate expects 1 argument, 0 provided
if (__beg == __end && __a == _Alloc())
^~~~~~~~
```

Where `_Alloc` is an alias to some instance of `folly::reentrant_allocator`.

The trouble is that this implementation of `std::basic_string` implicitly requires its allocator parameter to be default-constructible. This is a bug in the implementation of `std::basic_string`.

Unfortunately, `folly::reentrant_allocator` is not default-constructible and cannot reasonably be made to be default-constructible, since construction other than copy-construction is inordinately expensive and default construction is expected to be no more expensive than initializing fields to fixed values. So unfortunately I do not see a way that the bug can reasonably and locally be worked around within that implementation of `std::basic_string`.

This bug and related bugs only afflict the legacy libstdc++ ABI; the current ABI, as far as I know, does not suffer this and related bugs. One option, therefore, may be to switch to the current ABI.
