### ISSUE TITLE
MSVC error 15.8.2 format-inl.h error C4146: unary minus operator applied to unsigned type, result still unsigned

### ISSUE THREAD

**Issue by ghost** [facebook/folly#921]
Hello, cant build using Visual Studio 15.8.2 with Folly/Format.h

using Folly x64-windows 2018.07.30.00

```
1>------ Build started: Project: testing, Configuration: Debug x64 ------
1>testing.cpp
1>c:\vcpkg\installed\x64-windows\include\folly\format-inl.h(451): error C4146: unary minus operator applied to unsigned type, result still unsigned
```

Code that caused error: 
```
c:\vcpkg\installed\x64-windows\include\folly\format-inl.h(451)
if (std::is_signed<T>::value) {
      if (folly::is_negative(val_)) {
        uval = UT(-static_cast<UT>(val_));
        sign = '-';
      } else {
        uval = static_cast<UT>(val_);
```

I used vcpkg upgrade, but im pretty sure I had the --head version

**Comment by yfeldblum** [comment]
Closing because of age and because folly no longer supports VS 15.
