### ISSUE TITLE
Support glog 0.7.0

### ISSUE THREAD

**Issue by chenrui333** [facebook/folly#2171]
👋 trying to build fizz with glog 0.7.0, but ran into some regression test failure as below:

```
  ==> /usr/bin/clang++ -std=c++17 test.cpp -o test -I/opt/homebrew/Cellar/fizz/2024.04.01.00_1/include -I/opt/homebrew/opt/openssl@3/include -L/opt/homebrew/Cellar/fizz/2024.04.01.00_1/lib -lfizz -L/opt/homebrew/opt/folly/lib -lfolly -L/opt/homebrew/opt/gflags/lib -lgflags -L/opt/homebrew/opt/glog/lib -lglog -L/opt/homebrew/opt/libevent/lib -levent -L/opt/homebrew/opt/libsodium/lib -lsodium -L/opt/homebrew/opt/openssl@3/lib -lcrypto -lssl
  In file included from test.cpp:1:
  In file included from /opt/homebrew/Cellar/fizz/2024.04.01.00_1/include/fizz/client/AsyncFizzClient.h:11:
  In file included from /opt/homebrew/Cellar/fizz/2024.04.01.00_1/include/fizz/client/ClientExtensions.h:11:
  In file included from /opt/homebrew/Cellar/fizz/2024.04.01.00_1/include/fizz/record/Types.h:12:
  In file included from /opt/homebrew/include/folly/io/Cursor.h:31:
  In file included from /opt/homebrew/include/folly/io/IOBuf.h:33:
  /opt/homebrew/include/glog/logging.h:60:4: error: <glog/logging.h> was not included correctly. See the documention for how to consume the library.
  #  error <glog/logging.h> was not included correctly. See the documention for how to consume the library.
     ^
```

same failure seen for wangle as well.

relates to https://github.com/Homebrew/homebrew-core/pull/163094

**Comment by nh2** [comment]
Looks like Arch Linux AUR has a fix for this:

https://aur.archlinux.org/cgit/aur.git/tree/fix-cmake-find-glog.patch?h=folly

**Comment by nh2** [comment]
With PR #2245 and the above mentioned AUR patch, `folly` builds with `glog` 0.7.1 on NixOS.

**Comment by cho-m** [comment]
Looks like internal team went with their own fixes rather than any of the open PRs.
- Commits aad3ed861021a2aa9cf347f55ee8cdeaacd1aec0 9f0ea45dde54a693d44eb87d508371caea75da86 03e49d899b2bc00f41185425c82e4080cc2b6e73
- Open PRs that offered similar or alternative changes:
  - #2320
  - #2474
