### ISSUE TITLE
undefined reference to `jump_fcontext' on ubuntu 20.04

### ISSUE THREAD

**Issue by xgdgsc** [facebook/folly#1496]
```
make: *** [Makefile:130: all] Error 2
[ 93%] Built target folly_base
[ 93%] Built target folly
[ 94%] Built target folly_test_util
[ 95%] Built target follybenchmark
[ 96%] Built target folly_exception_tracer_base
[ 97%] Built target folly_exception_tracer
[ 98%] Built target folly_exception_counter
[ 99%] Built target logging_example_lib
[100%] Linking CXX executable logging_example
/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `jump_fcontext'
/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `make_fcontext'
collect2: error: ld returned 1 exit status
make[2]: *** [folly/logging/example/CMakeFiles/logging_example.dir/build.make:111: folly/logging/example/logging_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:367: folly/logging/example/CMakeFiles/logging_example.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```
I' m building with g++ 9.3.0, boost 1.68 on Ubuntu 20.04.

**Comment by xgdgsc** [comment]
Works with boost 1.69/

**Comment by ByteGatsby** [comment]
hi, How did you solve the problem? The same thing happened to me.

**Comment by xgdgsc** [comment]
As I mentioned above updating boost works.
