### ISSUE TITLE
folly-2018.03.12.00 gcc-6.4.0 folly/experimental/coro/tests/CoroTest.cpp failing

### ISSUE THREAD

**Issue by jlinoff** [facebook/folly#800]
I am  seeing this failure folly/experimental/coro/tests/CoroTest.cpp when trying to compile with gcc-6.4.0 on two CentOS hosts (version 6 and 7). Progress is at 17% so a lot a files compiled successfully. Can you provide any hints about how to debug this?

```
[ 17%] Building CXX object CMakeFiles/folly_base.dir/folly/experimental/coro/tests/CoroTest.cpp.o
In file included from /opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/Promise.h:22:0,
                 from /opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/Future.h:21,
                 from /opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/tests/CoroTest.cpp:17:
/opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/AwaitWrapper.h:30:10: error: ‘experimental’ in namespace ‘std’ does not name a type
     std::experimental::suspend_always initial_suspend() {
          ^~~~~~~~~~~~
/opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/AwaitWrapper.h:34:10: error: ‘experimental’ in namespace ‘std’ does not name a type
     std::experimental::suspend_never final_suspend() {
          ^~~~~~~~~~~~
/opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/AwaitWrapper.h:52:10: error: ‘experimental’ in namespace ‘std’ does not name a type
     std::experimental::coroutine_handle<> awaiter_;
          ^~~~~~~~~~~~
/opt/tool-chain/build/pkg/folly-2018.03.12.00/folly/experimental/coro/AwaitWrapper.h:73:35: error: ‘experimental’ is not a member of ‘std’
                    .await_suspend(std::experimental::coroutine_handle<>()));
                                   ^~~
```

**Comment by jlinoff** [comment]
It turns out gcc does not support `experimental/coroutines` so i need to turn to clang. I am doing that now.

**Comment by daniel-lucio** [comment]
For CentOS, check #929
