### ISSUE TITLE
error: static assertion failed: Big endian requires a redesigned table

### ISSUE THREAD

**Issue by barracuda156** [facebook/folly#1834]
Another error on 10.6.8 Rosetta with `gcc12`:
```
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_folly/folly/work/folly-v2022.08.01.00/folly/detail/base64_detail/Base64SWAR.cpp: In function 'uint32_t folly::detail::base64_detail::{anonymous}::base64DecodeSWARMainLoop(const char*&, const char*, char*&)':
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_folly/folly/work/folly-v2022.08.01.00/folly/detail/base64_detail/Base64SWAR.cpp:101:14: error: static assertion failed: Big endian requires a redesigned table
  101 |       folly::kIsLittleEndian, "Big endian requires a redesigned table");
      |       ~~~~~~~^~~~~~~~~~~~~~~
```

**Comment by barracuda156** [comment]
Source code leading to the error:
```
template <bool isURL>
std::uint32_t base64DecodeSWARMainLoop(
    const char*& f, const char* l, char*& o) noexcept {
  static_assert(
      folly::kIsLittleEndian, "Big endian requires a redesigned table");

  std::uint32_t errorAccumulator = 0;

  while (l - f > 4) {
    std::uint32_t r = //
        kBase64SwarDecodeTable<isURL>[0][atAsU8(f, 0)] |
        kBase64SwarDecodeTable<isURL>[1][atAsU8(f, 1)] |
        kBase64SwarDecodeTable<isURL>[2][atAsU8(f, 2)] |
        kBase64SwarDecodeTable<isURL>[3][atAsU8(f, 3)];

    errorAccumulator |= r;
    std::memcpy(o, &r, sizeof(r));

    f += 4;
    o += 3;
  }

  return errorAccumulator;
}
```

**Comment by barracuda156** [comment]
Looks like Big Endian have been broken forever with `folly`: https://bytemeta.vip/repo/facebook/folly/issues/1445

**Comment by barracuda156** [comment]
Now Big-endian is broken by https://github.com/facebook/folly/commit/1110819343455b5f698e8d01a951b9da1b3b9c5a commit.
