### ISSUE TITLE
Proxygen Linux compilation breaking in folly io_uring

### ISSUE THREAD

**Issue by moderation** [facebook/folly#1832]
Cross posted issue from https://github.com/facebookincubator/mvfst/issues/266

Compilation on Linux is breaking on the `folly` `io_uring` code. I've tried with gcc 12 and clang 14.0.6 and experimenting with `-std=gnu++20` and `-std=c++20` flags. Any ideas?

![image](https://user-images.githubusercontent.com/246317/180517560-196b747c-c511-4ff9-9d81-c80bff7e60b0.png)
```
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:548:18: error: non-type template parameters of class type only available with ‘-std=c++20’ or ‘-std=gnu++20’
  548 | template <class T...>
      |                  ^~~
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:549:17: error: ‘ProvidedBufferRing’ was not declared in this scope
  549 | std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing() {
      |                 ^~~~~~~~~~~~~~~~~~
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:549:35: error: template argument 1 is invalid
  549 | std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing() {
      |                                   ^
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:549:35: error: template argument 2 is invalid
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/external/farmhash/farmhash.cpp.o
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp: In constructor ‘folly::IoUringBackend::IoUringBackend(Options)’:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:734:22: error: ‘IORING_SETUP_COOP_TASKRUN’ was not declared in this scope
  734 |     params_.flags |= IORING_SETUP_COOP_TASKRUN;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp: In lambda function:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:774:11: error: ‘io_uring_register_ring_fd’ was not declared in this scope; did you mean ‘io_uring_register_eventfd’?
  774 |       if (io_uring_register_ring_fd(&ioRing_) < 0) {
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |           io_uring_register_eventfd
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp: In constructor ‘folly::IoUringBackend::IoUringBackend(Options)’:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:827:45: error: no matching function for call to ‘makeProvidedBufferRing(folly::IoUringBackend*, uint16_t, size_t&, int&, int&)’
  827 |     bufferProvider_ = makeProvidedBufferRing(
      |                       ~~~~~~~~~~~~~~~~~~~~~~^
  828 |         this,
      |         ~~~~~                                
  829 |         nextBufferProviderGid(),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~             
  830 |         options.initalProvidedBuffersCount,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  831 |         sizeShift,
      |         ~~~~~~~~~~                           
  832 |         ringShift);
      |         ~~~~~~~~~~                           
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:549:37: note: candidate: ‘template<<typeprefixerror>...<anonymous> > int folly::{anonymous}::makeProvidedBufferRing()’
  549 | std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing() {
      |                                     ^~~~~~~~~~~~~~~~~~~~~~
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:549:37: note:   template argument deduction/substitution failed:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:827:45: note:   candidate expects 0 arguments, 5 provided
  827 |     bufferProvider_ = makeProvidedBufferRing(
      |                       ~~~~~~~~~~~~~~~~~~~~~~^
  828 |         this,
      |         ~~~~~                                
  829 |         nextBufferProviderGid(),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~             
  830 |         options.initalProvidedBuffersCount,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  831 |         sizeShift,
      |         ~~~~~~~~~~                           
  832 |         ringShift);
      |         ~~~~~~~~~~                           
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/fibers/BatchSemaphore.cpp.o
[  6%] Building CXX object CMakeFiles/folly_base.dir/folly/fibers/Baton.cpp.o
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp: In member function ‘void folly::IoUringBackend::cancel(IoSqeBase*)’:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:1474:3: error: ‘io_uring_prep_cancel64’ was not declared in this scope; did you mean ‘io_uring_prep_cancel’?
 1474 |   io_uring_prep_cancel64(sqe, (uint64_t)ioSqe, 0);
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   io_uring_prep_cancel
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:1476:26: error: ‘IORING_FEAT_CQE_SKIP’ was not declared in this scope; did you mean ‘IORING_FEAT_NODROP’?
 1476 |   if (params_.features & IORING_FEAT_CQE_SKIP) {
      |                          ^~~~~~~~~~~~~~~~~~~~
      |                          IORING_FEAT_NODROP
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:1477:19: error: ‘IOSQE_CQE_SKIP_SUCCESS’ was not declared in this scope
 1477 |     sqe->flags |= IOSQE_CQE_SKIP_SUCCESS;
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp: In member function ‘bool folly::IoUringBackend::kernelHasNonBlockWriteFixes() const’:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:1830:29: error: ‘IORING_FEAT_LINKED_FILE’ was not declared in this scope
 1830 |   return params_.features & IORING_FEAT_LINKED_FILE;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/container/F14Map.h:42,
                 from /home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:23:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/container/detail/F14Policy.h: In instantiation of ‘folly::f14::detail::VectorContainerPolicy<Key, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, EligibleForPerturbedInsertionOrder>::Iter folly::f14::detail::VectorContainerPolicy<Key, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, EligibleForPerturbedInsertionOrder>::makeIter(const ItemIter&) const [with Key = std::__cxx11::basic_string<char>; MappedTypeOrVoid = folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo; HasherOrVoid = void; KeyEqualOrVoid = void; AllocOrVoid = void; EligibleForPerturbedInsertionOrder = std::integral_constant<bool, true>; Iter = folly::f14::detail::VectorContainerIterator<std::pair<const std::__cxx11::basic_string<char>, folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo>*>; ItemIter = folly::f14::detail::F14ItemIter<folly::f14::detail::F14Chunk<unsigned int>*>]’:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/container/F14Map.h:690:27:   required from ‘folly::f14::detail::F14BasicMap<Policy>::iterator folly::f14::detail::F14BasicMap<Policy>::find(const key_type&) [with Policy = folly::f14::detail::VectorContainerPolicy<std::__cxx11::basic_string<char>, folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo, void, void, void, std::integral_constant<bool, true> >; iterator = folly::f14::detail::VectorContainerIterator<std::pair<const std::__cxx11::basic_string<char>, folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo>*>; key_type = std::__cxx11::basic_string<char>]’
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:231:26:   required from here
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/container/detail/F14Policy.h:1450:42: warning: comparing the result of pointer addition ‘(((folly::f14::detail::VectorContainerPolicy<std::__cxx11::basic_string<char>, folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo, void, void, void, std::integral_constant<bool, true> >::ValuePtr)((const folly::f14::detail::VectorContainerPolicy<std::__cxx11::basic_string<char>, folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo, void, void, void, std::integral_constant<bool, true> >*)this)->folly::f14::detail::VectorContainerPolicy<std::__cxx11::basic_string<char>, folly::{anonymous}::SQGroupInfoRegistry::SQGroupInfo, void, void, void, std::integral_constant<bool, true> >::values_) + ((sizetype)(((long unsigned int)(& underlying)->folly::f14::detail::F14ItemIter<folly::f14::detail::F14Chunk<unsigned int>*>::item()) * 128)))’ and NULL [-Waddress]
 1450 |       assume(values_ + underlying.item() != nullptr);
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
[  6%] Building CXX object CMakeFiles/folly_base.dir/folly/fibers/Fiber.cpp.o
[  6%] Building CXX object CMakeFiles/folly_base.dir/folly/fibers/FiberManager.cpp.o
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp: In member function ‘void folly::{anonymous}::SignalRegistry::notify(int)’:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/experimental/io/IoUringBackend.cpp:81:14: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   81 |       ::write(fd, &sigNum, 1);
      |       ~~~~~~~^~~~~~~~~~~~~~~~
[  7%] Building CXX object CMakeFiles/folly_base.dir/folly/fibers/GuardPageAllocator.cpp.o
make[2]: *** [CMakeFiles/folly_base.dir/build.make:1686: CMakeFiles/folly_base.dir/folly/experimental/io/IoUringBackend.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/folly_base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by Orvid** [comment]
Ah, it looks like we have a minor syntax error on the fallback path, changing this line: https://github.com/facebook/folly/blob/main/folly/experimental/io/IoUringBackend.cpp#L541-542
to:
```
template <class... Args>
std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing(Args&&...) {
```

Should hopefully fix it. I'll put up a diff internally to get it fixed.

To get it working without that, building against a newer version of io_uring should also fix it.

**Comment by moderation** [comment]
Same errors with the patch above. Re: io_uring versions, this is on Xubuntu 22.04

```
uname -a
Linux hostname 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
apt-cache show liburing-dev
Package: liburing-dev
Architecture: amd64
Version: 2.1-2build1
Multi-Arch: same
Priority: optional
Section: libdevel
Source: liburing
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Guillem Jover <guillem@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 133
Depends: liburing2 (= 2.1-2build1), libc6-dev | libc-dev, linux-libc-dev (>= 5.1)
```

**Comment by moderation** [comment]
FWIW there are different errors when trying to build with clang 14.0.6
```
[  2%] Building CXX object CMakeFiles/folly_base.dir/folly/detail/AsyncTrace.cpp.o
In file included from /home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/compression/CompressionContextPoolSingletons.cpp:17:
In file included from /home/<user>/Downloads/proxygen/proxygen/_build/deps/folly/folly/compression/CompressionContextPoolSingletons.h:22:
/home/<user>/Downloads/proxygen/proxygen/_build/deps/include/zstd.h:191:1: error: an attribute list cannot appear here
ZSTD_DEPRECATED("Replaced by ZSTD_getFrameContentSize")
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/<user>/Downloads/proxygen/proxygen/_build/deps/include/zstd.h:49:38: note: expanded from macro 'ZSTD_DEPRECATED'
#    define ZSTD_DEPRECATED(message) [[deprecated(message)]]
                                     ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Orvid** [comment]
The iouring issues should be addressed by https://github.com/facebook/folly/commit/a41bdbadbb2fcf030bf19c81501001997559303e and https://github.com/facebook/folly/commit/ae20efa9fa8cea81079df519d93dcbd1523c8dc3

As-for the zstandard issue, @terrelln @Cyan4973 is this something either of you have seen before?

**Comment by Cyan4973** [comment]
It means that `folly` is using a deprecated entry point into `libzstd`. It will work, but triggers a deprecation warning by default.
The expectation is that user libraries shall update their code.
In this case, they shall move their invocation to `ZSTD_getFrameContentSize()`, which is a bit more correct to distinguish error cases, and separate errors rom "empty content" (which is not an error).
Other workaround include ignoring the warning, either at compilation level, or by using a `libzstd` provided build macro to silence this warning. Of course, this kind of defeats the point of this warning.

**Comment by Orvid** [comment]
This isn't a warning, it's clang complaining about the specific location that the attribute is at:
```
/home/<user>/Downloads/proxygen/proxygen/_build/deps/include/zstd.h:191:1: error: an attribute list cannot appear here
ZSTD_DEPRECATED("Replaced by ZSTD_getFrameContentSize")
```

**Comment by moderation** [comment]
Successfully building now with `gcc-12`! I ended up manually building and installing the latest `liburing`. `clang-14` still fails and I'll looking into updating `zstd`. Thanks for all of the troubleshooting and fixes
