### ISSUE TITLE
error: variable or field 'mainContext_' declared

### ISSUE THREAD

**Issue by dushibaiyu** [facebook/folly#342]
I was build iN opensuse leap 42.1 . gcc 4.8.5,boost 1.5.4.

mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT futures/Barrier.lo -MD -MP -MF futures/.deps/Barrier.Tpo -c futures/Barrier.cpp  -fPIC -DPIC -o futures/.libs/Barrier.o
In file included from ./../folly/experimental/fibers/Baton-inl.h:17:0,
                 from ./../folly/experimental/fibers/Baton.h:190,
                 from ./../folly/futures/Future-inl.h:24,
                 from ./../folly/futures/Future.h:487,
                 from ./../folly/futures/Barrier.h:22,
                 from futures/Barrier.cpp:17:
./../folly/experimental/fibers/FiberManager.h:324:27: error: variable or field 'mainContext_' declared void
   FContext::ContextStruct mainContext_;  /**< stores loop function context */
                           ^
In file included from ./../folly/experimental/fibers/FiberManager.h:518:0,
                 from ./../folly/experimental/fibers/Baton-inl.h:17,
                 from ./../folly/experimental/fibers/Baton.h:190,
                 from ./../folly/futures/Future-inl.h:24,
                 from ./../folly/futures/Future.h:487,
                 from ./../folly/futures/Barrier.h:22,
                 from futures/Barrier.cpp:17:
./../folly/experimental/fibers/FiberManager-inl.h: In member function 'void folly::fibers::FiberManager::runReadyFiber(folly::fibers::Fiber*)':
./../folly/experimental/fibers/FiberManager-inl.h:77:18: error: 'mainContext_' was not declared in this scope
     jumpContext(&mainContext_, &fiber->fcontext_, fiber->data_);
                  ^
Makefile:1249: recipe for target 'futures/Barrier.lo' failed
make[2]: *** [futures/Barrier.lo] Error 1
make[2]: Leaving directory '/public/code/cpp/folly-master/folly'
Makefile:1305: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/public/code/cpp/folly-master/folly'
Makefile:829: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dushibaiyu** [comment]
when i use boost 1.5.8,it is ok.but has other erro.
I use g++5.2.1 and boost 1.5.8 , the build is ok.
