### ISSUE TITLE
[Fedora 27] undefined reference to `TLS init function for folly::hazptr::tls_priv_data_

### ISSUE THREAD

**Issue by kornrunner** [facebook/folly#776]
I'm trying to compile current Folly 1d687403 on Fedora 27 and I'm ending up with following result:

```
[ 95%] Linking CXX executable GenerateFingerprintTables
CMakeFiles/folly_base.dir/folly/executors/TimedDrivableExecutor.cpp.o: In function `TLS wrapper function for folly::hazptr::tls_priv_data_':
TimedDrivableExecutor.cpp:(.text._ZTWN5folly6hazptr14tls_priv_data_E[_ZTWN5folly6hazptr14tls_priv_data_E]+0x5): undefined reference to `TLS init function for folly::hazptr::tls_priv_data_'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/GenerateFingerprintTables.dir/build.make:499: GenerateFingerprintTables] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/GenerateFingerprintTables.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Since `hazptr` is experimental, is there any way to skip it with some configure flag?
Or do you have any other solution? I can provide further info if required. Thanks!

**Comment by kornrunner** [comment]
Looks like the change was introduced in 2518ee5279e5d4f88b9feaea07e93048c2cb0229

**Comment by kornrunner** [comment]
And it's fixed in e6b2e78a072040c865fb0e2ca0a1f28018a39ee7

**Comment by yfeldblum** [comment]
Yeah, this looks like a bug in gcc7 that we have to work around.

**Comment by kornrunner** [comment]
Sorry to hijack this thread, but is there any chance for this https://github.com/facebook/mcrouter/pull/224 to get merged in (explained in https://github.com/facebook/mcrouter/issues/225)? It's completely unrelated, but I've got no feedback on it for quite a while...
