### ISSUE TITLE
 compiled error  for FBVector.h in release v2017.04.10.00 on centos

### ISSUE THREAD

**Issue by set-daemon** [facebook/folly#575]
centos6.5  g++ 3.8.1, folly version is release v2017.04.10.00.

compiling error as follows:
          FBVector.h:1432:49: error：parameter package can not be expand in‘...’：
                M_construct(start, std::forward<Args>(args)...);

thanks for your help.

**Comment by craveica** [comment]
same error in centos 7, gcc 4.8.5

**Comment by Orvid** [comment]
Support for GCC 4.8 in Folly is in the process of being dropped. I'll look into this if I get a chance, but there are significant changes being worked on that will definitely make Folly not compile on GCC 4.8, so I'd strongly recommend getting things upgraded to GCC 4.9 (devtoolset-3 is GCC 4.9 and is available for both centos 6 & 7)

**Comment by craveica** [comment]
@Orvid 

Using gcc 4.9 from devtoolset-3 solved my issue. Thank you.

**Comment by set-daemon** [comment]
@Orvid  Thanks, I'd udpdated the GCC 4.8.5 to 4.9.3,  then this problem solved.
