### ISSUE TITLE
macOS build failure "no matching function for call to 'max'"

### ISSUE THREAD

**Issue by ilovezfs** [facebook/folly#576]
Attempting to build folly 2017.04.10.00
```
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include   -std=gnu++1y -g -O2 -c -o io/Compression.lo io/Compression.cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c io/Compression.cpp  -fno-common -DPIC -o io/.libs/Compression.o
io/Compression.cpp:568:43: error: no matching function for call to 'max'
    const auto guessUncompressedLen = 4 * std::max(blockSize, in.size());
                                          ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2654:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long long' vs. 'unsigned long')
max(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2664:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'unsigned long long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2646:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2672:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
1 error generated.
make[2]: *** [io/Compression.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Full log is here: https://bot.brew.sh/job/Homebrew/job/homebrew-core/job/PR-12285/2/testReport/junit/brew-test-bot/sierra/install_folly/

Note that there is also a similar error for the `min` function if the max problem is hacked around.

**Comment by ilovezfs** [comment]
I induced this particular failure, rather than the one reported in #577, which occurs farther along, by deparallelizing the build.

**Comment by ilovezfs** [comment]
>Note that there is also a similar error for the min function if the max problem is hacked around.

@Orvid were those fixed too?

**Comment by terrelln** [comment]
All the calls to `std::min()` and `std::max()` in `folly/io/Compression.cpp` look okay to me. Is there a different `std::min()` call you are talking about?

**Comment by ilovezfs** [comment]
@terrelln I can't say at this point since we're back to this failure now:
```
experimental/EnvUtil.cpp:48:15: error: use of undeclared identifier 'clearenv'
  PCHECK(0 == clearenv());
              ^
1 error generated.
make[2]: *** [experimental/EnvUtil.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
@terrelln which also means https://github.com/facebook/folly/issues/567 should probably be reopened.

**Comment by ilovezfs** [comment]
@terrelln yup you're right. It looks fine. If I comment out line 48, the build finishes, so the min calls are fine.
