### ISSUE TITLE
Build Failure (Folly v2019.12.06.00, GCC 5.4.0, Ubuntu 16.04)

### ISSUE THREAD

**Issue by ystanislavyk** [facebook/folly#1274]
Greetings!

In the [Build Notes - Dependencies](https://github.com/facebook/folly#dependencies) section mentioned that folly requires gcc 5.1+.

I'm trying to build with the GCC 5.4.0 and getting the following error:
```
/workspace/folly/folly-2019.12.06.00/folly/experimental/SingleWriterFixedHashMap.h:52:32: error: 'is_always_lock_free' is not a member of 'std::atomic<bool>'
```

Also, there are a lot of warnings:
```
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h: In instantiation of 'class folly::SharedMutexImpl<true>::WriteHolder':
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1547:23:   required from here
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1444:25: warning: '__warn_unused_result__' attribute only applies to function types [-Wattributes]
   class FOLLY_NODISCARD WriteHolder {
                         ^
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h: In instantiation of 'class folly::SharedMutexImpl<true>::UpgradeHolder':
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1547:23:   required from here
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1394:25: warning: '__warn_unused_result__' attribute only applies to function types [-Wattributes]
   class FOLLY_NODISCARD UpgradeHolder {
                         ^
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h: In instantiation of 'class folly::SharedMutexImpl<true>::ReadHolder':
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1547:23:   required from here
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1332:25: warning: '__warn_unused_result__' attribute only applies to function types [-Wattributes]
   class FOLLY_NODISCARD ReadHolder {
                         ^
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h: In instantiation of 'class folly::SharedMutexImpl<false>::WriteHolder':
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1548:23:   required from here
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1444:25: warning: '__warn_unused_result__' attribute only applies to function types [-Wattributes]
   class FOLLY_NODISCARD WriteHolder {
                         ^
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h: In instantiation of 'class folly::SharedMutexImpl<false>::UpgradeHolder':
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1548:23:   required from here
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1394:25: warning: '__warn_unused_result__' attribute only applies to function types [-Wattributes]
   class FOLLY_NODISCARD UpgradeHolder {
                         ^
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h: In instantiation of 'class folly::SharedMutexImpl<false>::ReadHolder':
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1548:23:   required from here
/workspace/folly/folly-2019.12.06.00/folly/SharedMutex.h:1332:25: warning: '__warn_unused_result__' attribute only applies to function types [-Wattributes]
```

Although the build goes without the warnings and errors with the GCC 7.4.0 on Ubuntu 18.04.

The build is broken for the GCC 5 or the minimal GCC version was increased?

**Comment by Morheit** [comment]
I have tried to build Folly v2019.12.02.00 and v2019.11.11.00 with the GCC 5.4.0 and it's works.
It seems that build of Folly v2019.12.06.00 with the GCC 5.4.0 on is broken.

**Comment by xujiasci** [comment]
when you passed on Folly v2019.12.02.00 and v2019.11.11.00,did you see these warnings?

**Comment by xujiasci** [comment]
> I have tried to build Folly v2019.12.02.00 and v2019.11.11.00 with the GCC 5.4.0 and it works.
> It seems that build of Folly v2019.12.06.00 with the GCC 5.4.0 is broken.

when you passed on Folly v2019.12.02.00 and v2019.11.11.00,did you see these warnings?

**Comment by yfeldblum** [comment]
Closing this issue because it is to old and folly no longer targets Ubuntu 16.04 or GCC 5.
