### ISSUE TITLE
error: use of undeclared identifier 'DW_UT_compile

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1746]
The mvfst project fails to build with folly-2022.03.21.00:
```
In file included from /wrkdirs/usr/ports/net/mvfst/work/mvfst-31cadb557c903355e1ea04261f52e89098a68f99/quic/client/QuicClientAsyncTransport.cpp:11:
In file included from /usr/local/include/folly/experimental/symbolizer/Symbolizer.h:30:
In file included from /usr/local/include/folly/experimental/symbolizer/Dwarf.h:25:
/usr/local/include/folly/experimental/symbolizer/DwarfUtil.h:73:22: error: use of undeclared identifier 'DW_UT_compile'
  uint8_t unitType = DW_UT_compile; // DW_UT_compile or DW_UT_skeleton
                     ^
6 warnings and 1 error generated.
```

OS: FreeBSD 13

**Comment by wubiaoi** [comment]
How was it solved?

**Comment by yurivict** [comment]
This was solved by using devel/elfutils instead of some other library, can't recall the name now.

This was done in the context of the FreeBSD port.
