### ISSUE TITLE
Folly does not compile with GCC 7.3.0 and -fsanitize=thread

### ISSUE THREAD

**Issue by BenHuddleston** [facebook/folly#1084]
When compiling using -fsanitize=thread in GCC 7.3.0, a compilation error occurs because GCC 7.3.0 does not support the "no_sanitize" attribute. The current usages of the "no_sanitize" attribute when compiling with -fsanitize=thread are "undefined" and "nonnull-attribute". These can be replaced with the "no_sanitize_undefined" and "nonnull" attributes respectively.

There may be a similar issue when attempting to compile folly with -fsanitize=address but I've not investigated it.

I've created a pull request for this issue that does some feature checking and should still use the "no_sanitize" attribute if present https://github.com/facebook/folly/pull/1083.

**Comment by yfeldblum** [comment]
Closing because folly no longer supports gcc 7.
