### ISSUE TITLE
macOS 10.14 build failure

### ISSUE THREAD

**Issue by dtrodrigues** [facebook/folly#1532]
Folly fails to build on macOS 10.14

```
In file included from /tmp/folly-20210301-82287-orzki0/folly-2021.03.01.00/folly/ClockGettimeWrappers.cpp:17:
In file included from /tmp/folly-20210301-82287-orzki0/folly-2021.03.01.00/folly/ClockGettimeWrappers.h:19:
/tmp/folly-20210301-82287-orzki0/folly-2021.03.01.00/folly/portability/Time.h:52:17: error: typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')
typedef uint8_t clockid_t;
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
```

**Comment by dtrodrigues** [comment]
Closing per https://github.com/facebook/folly/issues/1545
