### ISSUE TITLE
Failure in running make check

### ISSUE THREAD

**Issue by banro21** [facebook/folly#508]
SynchronizedTest.cpp: In member function ‘virtual void SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()’:
SynchronizedTest.cpp:488:29: error: parameter declared ‘auto’
   sync.withULockPtr([](auto ulock) {
                             ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
SynchronizedTest.cpp: In lambda function:
SynchronizedTest.cpp:489:33: error: ‘ulock’ was not declared in this scope
     EXPECT_EQ(static_cast<bool>(ulock), true);
                                 ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
gtest-1.7.0/include/gtest/gtest.h:1924:32: note: in expansion of macro ‘GTEST_IS_NULL_LITERAL_’
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                ^
SynchronizedTest.cpp:489:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(ulock), true);
     ^
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:489:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(ulock), true);
     ^
SynchronizedTest.cpp:494:18: error: ‘ulock’ was not declared in this scope
     auto wlock = ulock.moveFromUpgradeToWrite();
                  ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:495:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(ulock), false);
     ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h: In instantiation of ‘auto folly::SynchronizedBase<Subclass, (folly::detail::MutexLevel)2>::withULockPtr(Function&&) [with Function = SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda43; Subclass = folly::Synchronized<int, FakeAllPowerfulAssertingMutex>]’:
SynchronizedTest.cpp:499:4:   required from here
../../folly/Synchronized.h:294:28: error: no match for call to ‘(SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda43) (folly::SynchronizedBase<folly::Synchronized<int, FakeAllPowerfulAssertingMutex>, (folly::detail::MutexLevel)2>::UpgradeLockedPtr)’
     return function(ulock());
                            ^
SynchronizedTest.cpp:488:22: note: candidates are:
   sync.withULockPtr([](auto ulock) {
                      ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h:294:28: note: void (*)() <conversion>
     return function(ulock());
                            ^
../../folly/Synchronized.h:294:28: note:   candidate expects 1 argument, 2 provided
SynchronizedTest.cpp:488:34: note: SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda43
   sync.withULockPtr([](auto ulock) {
                                  ^
SynchronizedTest.cpp:488:34: note:   candidate expects 0 arguments, 1 provided
SynchronizedTest.cpp: In member function ‘virtual void SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()’:
SynchronizedTest.cpp:507:29: error: parameter declared ‘auto’
   sync.withWLockPtr([](auto wlock) {
                             ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
SynchronizedTest.cpp: In lambda function:
SynchronizedTest.cpp:508:33: error: ‘wlock’ was not declared in this scope
     EXPECT_EQ(static_cast<bool>(wlock), true);
                                 ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
gtest-1.7.0/include/gtest/gtest.h:1924:32: note: in expansion of macro ‘GTEST_IS_NULL_LITERAL_’
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                ^
SynchronizedTest.cpp:508:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(wlock), true);
     ^
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:508:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(wlock), true);
     ^
SynchronizedTest.cpp:513:18: error: ‘wlock’ was not declared in this scope
     auto ulock = wlock.moveFromWriteToUpgrade();
                  ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:514:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(wlock), false);
     ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h: In instantiation of ‘auto folly::SynchronizedBase<Subclass, (folly::detail::MutexLevel)1>::withWLockPtr(Function&&) [with Function = SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda44; Subclass = folly::Synchronized<int, FakeAllPowerfulAssertingMutex>]’:
SynchronizedTest.cpp:518:4:   required from here
../../folly/Synchronized.h:180:28: error: no match for call to ‘(SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda44) (folly::SynchronizedBase<folly::Synchronized<int, FakeAllPowerfulAssertingMutex>, (folly::detail::MutexLevel)1>::LockedPtr)’
     return function(wlock());
                            ^
SynchronizedTest.cpp:507:22: note: candidates are:
   sync.withWLockPtr([](auto wlock) {
                      ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h:180:28: note: void (*)() <conversion>
     return function(wlock());
                            ^
../../folly/Synchronized.h:180:28: note:   candidate expects 1 argument, 2 provided
SynchronizedTest.cpp:507:34: note: SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda44
   sync.withWLockPtr([](auto wlock) {
                                  ^
SynchronizedTest.cpp:507:34: note:   candidate expects 0 arguments, 1 provided
SynchronizedTest.cpp: In member function ‘virtual void SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()’:
SynchronizedTest.cpp:526:29: error: parameter declared ‘auto’
   sync.withULockPtr([](auto ulock) {
                             ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
SynchronizedTest.cpp: In lambda function:
SynchronizedTest.cpp:527:33: error: ‘ulock’ was not declared in this scope
     EXPECT_EQ(static_cast<bool>(ulock), true);
                                 ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
gtest-1.7.0/include/gtest/gtest.h:1924:32: note: in expansion of macro ‘GTEST_IS_NULL_LITERAL_’
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                ^
SynchronizedTest.cpp:527:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(ulock), true);
     ^
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:527:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(ulock), true);
     ^
SynchronizedTest.cpp:532:18: error: ‘ulock’ was not declared in this scope
     auto slock = ulock.moveFromUpgradeToRead();
                  ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:533:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(ulock), false);
     ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h: In instantiation of ‘auto folly::SynchronizedBase<Subclass, (folly::detail::MutexLevel)2>::withULockPtr(Function&&) [with Function = SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda45; Subclass = folly::Synchronized<int, FakeAllPowerfulAssertingMutex>]’:
SynchronizedTest.cpp:537:4:   required from here
../../folly/Synchronized.h:294:28: error: no match for call to ‘(SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda45) (folly::SynchronizedBase<folly::Synchronized<int, FakeAllPowerfulAssertingMutex>, (folly::detail::MutexLevel)2>::UpgradeLockedPtr)’
     return function(ulock());
                            ^
SynchronizedTest.cpp:526:22: note: candidates are:
   sync.withULockPtr([](auto ulock) {
                      ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h:294:28: note: void (*)() <conversion>
     return function(ulock());
                            ^
../../folly/Synchronized.h:294:28: note:   candidate expects 1 argument, 2 provided
SynchronizedTest.cpp:526:34: note: SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda45
   sync.withULockPtr([](auto ulock) {
                                  ^
SynchronizedTest.cpp:526:34: note:   candidate expects 0 arguments, 1 provided
SynchronizedTest.cpp: In member function ‘virtual void SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()’:
SynchronizedTest.cpp:545:29: error: parameter declared ‘auto’
   sync.withWLockPtr([](auto wlock) {
                             ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
SynchronizedTest.cpp: In lambda function:
SynchronizedTest.cpp:546:33: error: ‘wlock’ was not declared in this scope
     EXPECT_EQ(static_cast<bool>(wlock), true);
                                 ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
gtest-1.7.0/include/gtest/gtest.h:1924:32: note: in expansion of macro ‘GTEST_IS_NULL_LITERAL_’
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                ^
SynchronizedTest.cpp:546:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(wlock), true);
     ^
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:546:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(wlock), true);
     ^
SynchronizedTest.cpp:551:18: error: ‘wlock’ was not declared in this scope
     auto slock = wlock.moveFromWriteToRead();
                  ^
In file included from gtest-1.7.0/include/gtest/gtest.h:1874:0,
                 from ../../folly/portability/GTest.h:25,
                 from ../../folly/test/SynchronizedTestLib-inl.h:22,
                 from ../../folly/test/SynchronizedTestLib.h:64,
                 from SynchronizedTest.cpp:27:
gtest-1.7.0/include/gtest/gtest.h:1924:60: error: template argument 1 is invalid
                       EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                            ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
gtest-1.7.0/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
gtest-1.7.0/include/gtest/gtest.h:1923:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
SynchronizedTest.cpp:552:5: note: in expansion of macro ‘EXPECT_EQ’
     EXPECT_EQ(static_cast<bool>(wlock), false);
     ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h: In instantiation of ‘auto folly::SynchronizedBase<Subclass, (folly::detail::MutexLevel)1>::withWLockPtr(Function&&) [with Function = SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda46; Subclass = folly::Synchronized<int, FakeAllPowerfulAssertingMutex>]’:
SynchronizedTest.cpp:556:4:   required from here
../../folly/Synchronized.h:180:28: error: no match for call to ‘(SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda46) (folly::SynchronizedBase<folly::Synchronized<int, FakeAllPowerfulAssertingMutex>, (folly::detail::MutexLevel)1>::LockedPtr)’
     return function(wlock());
                            ^
SynchronizedTest.cpp:545:22: note: candidates are:
   sync.withWLockPtr([](auto wlock) {
                      ^
In file included from SynchronizedTest.cpp:26:0:
../../folly/Synchronized.h:180:28: note: void (*)() <conversion>
     return function(wlock());
                            ^
../../folly/Synchronized.h:180:28: note:   candidate expects 1 argument, 2 provided
SynchronizedTest.cpp:545:34: note: SynchronizedLockTest_UpgradableLockingWithULock_Test::TestBody()::__lambda46
   sync.withWLockPtr([](auto wlock) {
                                  ^
SynchronizedTest.cpp:545:34: note:   candidate expects 0 arguments, 1 provided
make[3]: *** [SynchronizedTest.o] Error 1
make[3]: Leaving directory `/home/xxx/github/folly/folly/test'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/xxx/github/folly/folly/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/xxx/github/folly/folly/test'
make: *** [check-recursive] Error 1

**Comment by Arsey** [comment]
I'm getting the same error

**Comment by juesato** [comment]
Also getting the same error - has anybody made progress on this? I suspect the issue has to do with incompatible versions of gtest (I got the version from `curl -JLOk https://github.com/google/googletest/archive/release-1.7.0.zip` since the link on the folly instructions doesn't point to anything any more).

**Comment by Orvid** [comment]
It looks like one of the synchronized tests is using a C++14 feature which isn't available with GCC 4.8, specifically generic lambdas.

**Comment by juesato** [comment]
Ahhh that makes a lot of sense. Is removing the test to install folly reasonable? Or will folly just not work with GCC 4.8?

**Comment by Orvid** [comment]
Folly itself works fine with GCC 4.8, removing the test is fine. It really shouldn't be using that feature :(

**Comment by juesato** [comment]
Okay, thank you! I'll try this (takes a while since I need to rerun make) and let you know

**Comment by juesato** [comment]
Hm now I'm getting 
```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -g -O2 -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono   -lssl -lcrypto    -o mallctl_helper_test MallctlHelperTest.o libfollytestmain.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags 
libtool: link: g++ -std=gnu++1y -g -O2 -o .libs/mallctl_helper_test MallctlHelperTest.o  ./.libs/libfollytestmain.a /home/juesato/Downloads/folly/folly/.libs/libfolly.so -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags
MallctlHelperTest.o: In function `main':
/home/juesato/Downloads/folly/folly/test/MallctlHelperTest.cpp:94: undefined reference to `folly::init(int*, char***, bool)'
```
which seems bad. Do you know if this is related? Sorry for the trouble

**Comment by Orvid** [comment]
It's unrelated, it looks like we don't have that test marked as being dependent on folly::init like it's supposed to be. Feel free to disable it as well.

**Comment by juesato** [comment]
Sorry for the trouble @Orvid I don't think I need help with this any more.

I was setting up folly so that another Facebook library (fblualib/python) could work, since that install wasn't working well without folly, but it seems like there's a lot I'd have to do even after fixing this to install that properly, and I think I can find a way to do what I'm doing without the library.
